INSERT INTO categories (id,maincategory,subcategory) VALUES (1,'Arts','Animation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (2,'Arts','Architecture');
INSERT INTO categories (id,maincategory,subcategory) VALUES (3,'Arts','Art History');
INSERT INTO categories (id,maincategory,subcategory) VALUES (4,'Arts','Artists');
INSERT INTO categories (id,maincategory,subcategory) VALUES (5,'Arts','Arts and Crafts');
INSERT INTO categories (id,maincategory,subcategory) VALUES (6,'Arts','Awards');
INSERT INTO categories (id,maincategory,subcategory) VALUES (7,'Arts','Body Art');
INSERT INTO categories (id,maincategory,subcategory) VALUES (8,'Arts','Bodyart');
INSERT INTO categories (id,maincategory,subcategory) VALUES (9,'Arts','Ceramics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (10,'Arts','Classical Studies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (11,'Arts','Comics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (12,'Arts','Computer Generated');
INSERT INTO categories (id,maincategory,subcategory) VALUES (13,'Arts','Costumes');
INSERT INTO categories (id,maincategory,subcategory) VALUES (14,'Arts','Crafts');
INSERT INTO categories (id,maincategory,subcategory) VALUES (15,'Arts','Cultures and Groups');
INSERT INTO categories (id,maincategory,subcategory) VALUES (16,'Arts','Design');
INSERT INTO categories (id,maincategory,subcategory) VALUES (17,'Arts','Digital');
INSERT INTO categories (id,maincategory,subcategory) VALUES (18,'Arts','Directories');
INSERT INTO categories (id,maincategory,subcategory) VALUES (19,'Arts','Entertainment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (20,'Arts','Genres');
INSERT INTO categories (id,maincategory,subcategory) VALUES (21,'Arts','Graphic Design');
INSERT INTO categories (id,maincategory,subcategory) VALUES (22,'Arts','Humanities');
INSERT INTO categories (id,maincategory,subcategory) VALUES (23,'Arts','Illustration');
INSERT INTO categories (id,maincategory,subcategory) VALUES (24,'Arts','Literature');
INSERT INTO categories (id,maincategory,subcategory) VALUES (25,'Arts','Movies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (26,'Arts','Music');
INSERT INTO categories (id,maincategory,subcategory) VALUES (27,'Arts','Online Writing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (28,'Arts','Organizations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (29,'Arts','Performing Arts');
INSERT INTO categories (id,maincategory,subcategory) VALUES (30,'Arts','Periods and Movements');
INSERT INTO categories (id,maincategory,subcategory) VALUES (31,'Arts','Photography');
INSERT INTO categories (id,maincategory,subcategory) VALUES (32,'Arts','Quilting');
INSERT INTO categories (id,maincategory,subcategory) VALUES (33,'Arts','Radio');
INSERT INTO categories (id,maincategory,subcategory) VALUES (34,'Arts','Sculpture');
INSERT INTO categories (id,maincategory,subcategory) VALUES (35,'Arts','Television');
INSERT INTO categories (id,maincategory,subcategory) VALUES (36,'Arts','Video');
INSERT INTO categories (id,maincategory,subcategory) VALUES (37,'Arts','Visual Arts');
INSERT INTO categories (id,maincategory,subcategory) VALUES (38,'Arts','Writers Resources');
INSERT INTO categories (id,maincategory,subcategory) VALUES (39,'Business','Accounting');
INSERT INTO categories (id,maincategory,subcategory) VALUES (40,'Business','Advertising');
INSERT INTO categories (id,maincategory,subcategory) VALUES (41,'Business','Aerospace and Defense');
INSERT INTO categories (id,maincategory,subcategory) VALUES (42,'Business','Agriculture');
INSERT INTO categories (id,maincategory,subcategory) VALUES (43,'Business','Agriculture and Forestry');
INSERT INTO categories (id,maincategory,subcategory) VALUES (44,'Business','Arts and Entertainment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (45,'Business','Associations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (46,'Business','Automotive');
INSERT INTO categories (id,maincategory,subcategory) VALUES (47,'Business','Banking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (48,'Business','Biotechnology and Pharmaceuticals');
INSERT INTO categories (id,maincategory,subcategory) VALUES (49,'Business','Business and Society');
INSERT INTO categories (id,maincategory,subcategory) VALUES (50,'Business','Business Services');
INSERT INTO categories (id,maincategory,subcategory) VALUES (51,'Business','Chemicals');
INSERT INTO categories (id,maincategory,subcategory) VALUES (52,'Business','Construction');
INSERT INTO categories (id,maincategory,subcategory) VALUES (53,'Business','Construction and Maintenance');
INSERT INTO categories (id,maincategory,subcategory) VALUES (54,'Business','Consulting');
INSERT INTO categories (id,maincategory,subcategory) VALUES (55,'Business','Consumer Goods and Services');
INSERT INTO categories (id,maincategory,subcategory) VALUES (56,'Business','Cooperatives');
INSERT INTO categories (id,maincategory,subcategory) VALUES (57,'Business','Customer Service');
INSERT INTO categories (id,maincategory,subcategory) VALUES (58,'Business','Education and Training');
INSERT INTO categories (id,maincategory,subcategory) VALUES (59,'Business','Electronics and Electrical');
INSERT INTO categories (id,maincategory,subcategory) VALUES (60,'Business','Employment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (61,'Business','Energy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (62,'Business','Environment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (63,'Business','Financial');
INSERT INTO categories (id,maincategory,subcategory) VALUES (64,'Business','Financial Services');
INSERT INTO categories (id,maincategory,subcategory) VALUES (65,'Business','Food');
INSERT INTO categories (id,maincategory,subcategory) VALUES (66,'Business','Food and Related Products');
INSERT INTO categories (id,maincategory,subcategory) VALUES (67,'Business','Healthcare');
INSERT INTO categories (id,maincategory,subcategory) VALUES (68,'Business','Hospitality');
INSERT INTO categories (id,maincategory,subcategory) VALUES (69,'Business','Human Resources');
INSERT INTO categories (id,maincategory,subcategory) VALUES (70,'Business','Industrial Goods and Services');
INSERT INTO categories (id,maincategory,subcategory) VALUES (71,'Business','Information Services');
INSERT INTO categories (id,maincategory,subcategory) VALUES (72,'Business','Information Technology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (73,'Business','Insurance');
INSERT INTO categories (id,maincategory,subcategory) VALUES (74,'Business','International Business and Trade');
INSERT INTO categories (id,maincategory,subcategory) VALUES (75,'Business','Internet');
INSERT INTO categories (id,maincategory,subcategory) VALUES (76,'Business','Investing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (77,'Business','Legal');
INSERT INTO categories (id,maincategory,subcategory) VALUES (78,'Business','Major Companies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (79,'Business','Management');
INSERT INTO categories (id,maincategory,subcategory) VALUES (80,'Business','Manufacturing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (81,'Business','Marketing and Advertising');
INSERT INTO categories (id,maincategory,subcategory) VALUES (82,'Business','Marketing and Sales');
INSERT INTO categories (id,maincategory,subcategory) VALUES (83,'Business','Materials');
INSERT INTO categories (id,maincategory,subcategory) VALUES (84,'Business','Mining');
INSERT INTO categories (id,maincategory,subcategory) VALUES (85,'Business','Mining and Drilling');
INSERT INTO categories (id,maincategory,subcategory) VALUES (86,'Business','Opportunities');
INSERT INTO categories (id,maincategory,subcategory) VALUES (87,'Business','Publishing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (88,'Business','Publishing and Printing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (89,'Business','Real Estate');
INSERT INTO categories (id,maincategory,subcategory) VALUES (90,'Business','Resources');
INSERT INTO categories (id,maincategory,subcategory) VALUES (91,'Business','Retail Trade');
INSERT INTO categories (id,maincategory,subcategory) VALUES (92,'Business','Security');
INSERT INTO categories (id,maincategory,subcategory) VALUES (93,'Business','Small Business');
INSERT INTO categories (id,maincategory,subcategory) VALUES (94,'Business','Telecommunications');
INSERT INTO categories (id,maincategory,subcategory) VALUES (95,'Business','Textiles and Nonwovens');
INSERT INTO categories (id,maincategory,subcategory) VALUES (96,'Business','Transportation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (97,'Business','Transportation and Logistics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (98,'Business','Wholesale Trade');
INSERT INTO categories (id,maincategory,subcategory) VALUES (99,'Computers','Algorithms');
INSERT INTO categories (id,maincategory,subcategory) VALUES (100,'Computers','Artificial Intelligence');
INSERT INTO categories (id,maincategory,subcategory) VALUES (101,'Computers','Artificial Life');
INSERT INTO categories (id,maincategory,subcategory) VALUES (102,'Computers','Automation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (103,'Computers','Bulletin Board Systems');
INSERT INTO categories (id,maincategory,subcategory) VALUES (104,'Computers','CAD and CAM');
INSERT INTO categories (id,maincategory,subcategory) VALUES (105,'Computers','Companies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (106,'Computers','Computer Arts');
INSERT INTO categories (id,maincategory,subcategory) VALUES (107,'Computers','Computer Science');
INSERT INTO categories (id,maincategory,subcategory) VALUES (108,'Computers','Consultants');
INSERT INTO categories (id,maincategory,subcategory) VALUES (109,'Computers','Data Communications');
INSERT INTO categories (id,maincategory,subcategory) VALUES (110,'Computers','Data Formats');
INSERT INTO categories (id,maincategory,subcategory) VALUES (111,'Computers','Databases');
INSERT INTO categories (id,maincategory,subcategory) VALUES (112,'Computers','Desktop Publishing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (113,'Computers','E-Books');
INSERT INTO categories (id,maincategory,subcategory) VALUES (114,'Computers','E-Commerce');
INSERT INTO categories (id,maincategory,subcategory) VALUES (115,'Computers','Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (116,'Computers','Emulators');
INSERT INTO categories (id,maincategory,subcategory) VALUES (117,'Computers','Ethics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (118,'Computers','Games');
INSERT INTO categories (id,maincategory,subcategory) VALUES (119,'Computers','Graphics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (120,'Computers','Hacking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (121,'Computers','Hardware');
INSERT INTO categories (id,maincategory,subcategory) VALUES (122,'Computers','History');
INSERT INTO categories (id,maincategory,subcategory) VALUES (123,'Computers','Home Automation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (124,'Computers','Human-Computer Interaction');
INSERT INTO categories (id,maincategory,subcategory) VALUES (125,'Computers','Internet');
INSERT INTO categories (id,maincategory,subcategory) VALUES (126,'Computers','Intranet');
INSERT INTO categories (id,maincategory,subcategory) VALUES (127,'Computers','Java');
INSERT INTO categories (id,maincategory,subcategory) VALUES (128,'Computers','Macintosh');
INSERT INTO categories (id,maincategory,subcategory) VALUES (129,'Computers','Microprocessors');
INSERT INTO categories (id,maincategory,subcategory) VALUES (130,'Computers','Mobile Computing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (131,'Computers','Multimedia');
INSERT INTO categories (id,maincategory,subcategory) VALUES (132,'Computers','Networking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (133,'Computers','Object Oriented');
INSERT INTO categories (id,maincategory,subcategory) VALUES (134,'Computers','Open Source');
INSERT INTO categories (id,maincategory,subcategory) VALUES (135,'Computers','Operating Systems');
INSERT INTO categories (id,maincategory,subcategory) VALUES (136,'Computers','Organizations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (137,'Computers','Parallel Computing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (138,'Computers','Performance and Capacity');
INSERT INTO categories (id,maincategory,subcategory) VALUES (139,'Computers','Programming');
INSERT INTO categories (id,maincategory,subcategory) VALUES (140,'Computers','Programming Languages');
INSERT INTO categories (id,maincategory,subcategory) VALUES (141,'Computers','Robotics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (142,'Computers','Security');
INSERT INTO categories (id,maincategory,subcategory) VALUES (143,'Computers','Software');
INSERT INTO categories (id,maincategory,subcategory) VALUES (144,'Computers','Speech Technology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (145,'Computers','Supercomputing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (146,'Computers','Systems');
INSERT INTO categories (id,maincategory,subcategory) VALUES (147,'Computers','Unix');
INSERT INTO categories (id,maincategory,subcategory) VALUES (148,'Computers','Usenet');
INSERT INTO categories (id,maincategory,subcategory) VALUES (149,'Computers','Virtual Reality');
INSERT INTO categories (id,maincategory,subcategory) VALUES (150,'Computers','World Wide Web');
INSERT INTO categories (id,maincategory,subcategory) VALUES (151,'Consumers','Apartment Living');
INSERT INTO categories (id,maincategory,subcategory) VALUES (152,'Consumers','Consumer Information');
INSERT INTO categories (id,maincategory,subcategory) VALUES (153,'Consumers','Cooking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (154,'Consumers','Do-It-Yourself');
INSERT INTO categories (id,maincategory,subcategory) VALUES (155,'Consumers','Emergency Preparation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (156,'Consumers','Entertaining');
INSERT INTO categories (id,maincategory,subcategory) VALUES (157,'Consumers','Family');
INSERT INTO categories (id,maincategory,subcategory) VALUES (158,'Consumers','Gardening');
INSERT INTO categories (id,maincategory,subcategory) VALUES (159,'Consumers','Home Improvement');
INSERT INTO categories (id,maincategory,subcategory) VALUES (160,'Consumers','Homemaking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (161,'Consumers','Homeowners');
INSERT INTO categories (id,maincategory,subcategory) VALUES (162,'Consumers','Moving and Relocating');
INSERT INTO categories (id,maincategory,subcategory) VALUES (163,'Consumers','Personal Finance');
INSERT INTO categories (id,maincategory,subcategory) VALUES (164,'Consumers','Personal Organization');
INSERT INTO categories (id,maincategory,subcategory) VALUES (165,'Consumers','Rural Living');
INSERT INTO categories (id,maincategory,subcategory) VALUES (166,'Consumers','Urban Living');
INSERT INTO categories (id,maincategory,subcategory) VALUES (167,'Education','Adolescence Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (168,'Education','Adult Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (169,'Education','Advanced Quantitative Methods in Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (170,'Education','Business Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (171,'Education','Christian School Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (172,'Education','Communication Disorders and Sciences');
INSERT INTO categories (id,maincategory,subcategory) VALUES (173,'Education','Community Development and Action');
INSERT INTO categories (id,maincategory,subcategory) VALUES (174,'Education','Critical and Socio-cultural Studies in Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (175,'Education','Curriculum and Instruction');
INSERT INTO categories (id,maincategory,subcategory) VALUES (176,'Education','Distance Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (177,'Education','Early Childhood Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (178,'Education','Education for Hearing Impaired');
INSERT INTO categories (id,maincategory,subcategory) VALUES (179,'Education','Educational Administration');
INSERT INTO categories (id,maincategory,subcategory) VALUES (180,'Education','Educational Leadership');
INSERT INTO categories (id,maincategory,subcategory) VALUES (181,'Education','Elementary Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (182,'Education','English as a Second Language');
INSERT INTO categories (id,maincategory,subcategory) VALUES (183,'Education','English Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (184,'Education','Environmental Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (185,'Education','Financial Aid');
INSERT INTO categories (id,maincategory,subcategory) VALUES (186,'Education','General Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (187,'Education','Health Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (188,'Education','Higher Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (189,'Education','History Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (190,'Education','Home Schooling');
INSERT INTO categories (id,maincategory,subcategory) VALUES (191,'Education','Human Resource Development');
INSERT INTO categories (id,maincategory,subcategory) VALUES (192,'Education','Information Studies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (193,'Education','Instructional Technology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (194,'Education','International Comparative Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (195,'Education','K12 Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (196,'Education','Languages');
INSERT INTO categories (id,maincategory,subcategory) VALUES (197,'Education','Learning and Organizational Change');
INSERT INTO categories (id,maincategory,subcategory) VALUES (198,'Education','Learning Diversity and Urban Studies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (199,'Education','Library Resource Management');
INSERT INTO categories (id,maincategory,subcategory) VALUES (200,'Education','Literacy Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (201,'Education','Math Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (202,'Education','Middle Grades Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (203,'Education','Mind Brain and Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (204,'Education','Montessori Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (205,'Education','Music Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (206,'Education','Physical Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (207,'Education','Reading Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (208,'Education','Research Art Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (209,'Education','Risk and Prevention');
INSERT INTO categories (id,maincategory,subcategory) VALUES (210,'Education','School Counseling');
INSERT INTO categories (id,maincategory,subcategory) VALUES (211,'Education','School Health Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (212,'Education','School Psychology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (213,'Education','School Safety');
INSERT INTO categories (id,maincategory,subcategory) VALUES (214,'Education','Science Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (215,'Education','Secondary Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (216,'Education','Social Research Methodology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (217,'Education','Social Studies Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (218,'Education','Special Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (219,'Education','Talented and Gifted Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (220,'Education','Teacher Education Program');
INSERT INTO categories (id,maincategory,subcategory) VALUES (221,'Education','Technical and Vocational');
INSERT INTO categories (id,maincategory,subcategory) VALUES (222,'Education','Technology Innovation and Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (223,'Education','Visually Impaired Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (224,'Geographical','Africa');
INSERT INTO categories (id,maincategory,subcategory) VALUES (225,'Geographical','Asia');
INSERT INTO categories (id,maincategory,subcategory) VALUES (226,'Geographical','Caribbean');
INSERT INTO categories (id,maincategory,subcategory) VALUES (227,'Geographical','Central America');
INSERT INTO categories (id,maincategory,subcategory) VALUES (228,'Geographical','Countries');
INSERT INTO categories (id,maincategory,subcategory) VALUES (229,'Geographical','Europe');
INSERT INTO categories (id,maincategory,subcategory) VALUES (230,'Geographical','Middle East');
INSERT INTO categories (id,maincategory,subcategory) VALUES (231,'Geographical','Middle East');
INSERT INTO categories (id,maincategory,subcategory) VALUES (232,'Geographical','North America');
INSERT INTO categories (id,maincategory,subcategory) VALUES (233,'Geographical','Oceania');
INSERT INTO categories (id,maincategory,subcategory) VALUES (234,'Geographical','Polar Regions');
INSERT INTO categories (id,maincategory,subcategory) VALUES (235,'Geographical','South America');
INSERT INTO categories (id,maincategory,subcategory) VALUES (236,'Health','Addictions');
INSERT INTO categories (id,maincategory,subcategory) VALUES (237,'Health','Aging');
INSERT INTO categories (id,maincategory,subcategory) VALUES (238,'Health','AIDS');
INSERT INTO categories (id,maincategory,subcategory) VALUES (239,'Health','Alternative');
INSERT INTO categories (id,maincategory,subcategory) VALUES (240,'Health','Animal');
INSERT INTO categories (id,maincategory,subcategory) VALUES (241,'Health','Beauty');
INSERT INTO categories (id,maincategory,subcategory) VALUES (242,'Health','Child Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (243,'Health','Conditions and Diseases');
INSERT INTO categories (id,maincategory,subcategory) VALUES (244,'Health','Dentistry');
INSERT INTO categories (id,maincategory,subcategory) VALUES (245,'Health','Disabilities');
INSERT INTO categories (id,maincategory,subcategory) VALUES (246,'Health','Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (247,'Health','Environmental');
INSERT INTO categories (id,maincategory,subcategory) VALUES (248,'Health','Fitness');
INSERT INTO categories (id,maincategory,subcategory) VALUES (249,'Health','Home Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (250,'Health','Insurance');
INSERT INTO categories (id,maincategory,subcategory) VALUES (251,'Health','Long Term');
INSERT INTO categories (id,maincategory,subcategory) VALUES (252,'Health','Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (253,'Health','Men''s Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (254,'Health','Mental');
INSERT INTO categories (id,maincategory,subcategory) VALUES (255,'Health','Mental Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (256,'Health','Neurology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (257,'Health','Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (258,'Health','Nutrition');
INSERT INTO categories (id,maincategory,subcategory) VALUES (259,'Health','Occupational Health and Safety');
INSERT INTO categories (id,maincategory,subcategory) VALUES (260,'Health','Organizations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (261,'Health','Pharmacy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (262,'Health','Physiology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (263,'Health','Professions');
INSERT INTO categories (id,maincategory,subcategory) VALUES (264,'Health','Public Health and Safety');
INSERT INTO categories (id,maincategory,subcategory) VALUES (265,'Health','Publications');
INSERT INTO categories (id,maincategory,subcategory) VALUES (266,'Health','Reproductive Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (267,'Health','Resources');
INSERT INTO categories (id,maincategory,subcategory) VALUES (268,'Health','Senior Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (269,'Health','Senses');
INSERT INTO categories (id,maincategory,subcategory) VALUES (270,'Health','Services');
INSERT INTO categories (id,maincategory,subcategory) VALUES (271,'Health','Specific Substances');
INSERT INTO categories (id,maincategory,subcategory) VALUES (272,'Health','Teen Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (273,'Health','Veterinary');
INSERT INTO categories (id,maincategory,subcategory) VALUES (274,'Health','Weight Loss');
INSERT INTO categories (id,maincategory,subcategory) VALUES (275,'Health','Women''s Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (276,'Law','Administrative and Regulatory');
INSERT INTO categories (id,maincategory,subcategory) VALUES (277,'Law','Admiralty and Maritime');
INSERT INTO categories (id,maincategory,subcategory) VALUES (278,'Law','Air Sea and Space');
INSERT INTO categories (id,maincategory,subcategory) VALUES (279,'Law','Antitrust');
INSERT INTO categories (id,maincategory,subcategory) VALUES (280,'Law','Appellate');
INSERT INTO categories (id,maincategory,subcategory) VALUES (281,'Law','Banking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (282,'Law','Bankruptcy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (283,'Law','Business');
INSERT INTO categories (id,maincategory,subcategory) VALUES (284,'Law','Business Bankruptcy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (285,'Law','Childrens Advocacy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (286,'Law','Civil Rights');
INSERT INTO categories (id,maincategory,subcategory) VALUES (287,'Law','Civil Trial Advocacy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (288,'Law','Consumer Bankruptcy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (289,'Law','Creditors Rights');
INSERT INTO categories (id,maincategory,subcategory) VALUES (290,'Law','Criminal');
INSERT INTO categories (id,maincategory,subcategory) VALUES (291,'Law','Criminal Trial Advocacy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (292,'Law','Cyberspace');
INSERT INTO categories (id,maincategory,subcategory) VALUES (293,'Law','Disability');
INSERT INTO categories (id,maincategory,subcategory) VALUES (294,'Law','Drug');
INSERT INTO categories (id,maincategory,subcategory) VALUES (295,'Law','e-Commerce');
INSERT INTO categories (id,maincategory,subcategory) VALUES (296,'Law','Elder');
INSERT INTO categories (id,maincategory,subcategory) VALUES (297,'Law','Employment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (298,'Law','Entertainment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (299,'Law','Environmental');
INSERT INTO categories (id,maincategory,subcategory) VALUES (300,'Law','Estate Planning Trust and Probate');
INSERT INTO categories (id,maincategory,subcategory) VALUES (301,'Law','Family');
INSERT INTO categories (id,maincategory,subcategory) VALUES (302,'Law','Family Trial Advocacy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (303,'Law','Fashion');
INSERT INTO categories (id,maincategory,subcategory) VALUES (304,'Law','Franchise and Distribution');
INSERT INTO categories (id,maincategory,subcategory) VALUES (305,'Law','Gaming');
INSERT INTO categories (id,maincategory,subcategory) VALUES (306,'Law','Health');
INSERT INTO categories (id,maincategory,subcategory) VALUES (307,'Law','Immigration and Nationality');
INSERT INTO categories (id,maincategory,subcategory) VALUES (308,'Law','Insurance');
INSERT INTO categories (id,maincategory,subcategory) VALUES (309,'Law','Intellectual Property');
INSERT INTO categories (id,maincategory,subcategory) VALUES (310,'Law','Judicial');
INSERT INTO categories (id,maincategory,subcategory) VALUES (311,'Law','Legal Malpractice');
INSERT INTO categories (id,maincategory,subcategory) VALUES (312,'Law','Legal Professional Liability');
INSERT INTO categories (id,maincategory,subcategory) VALUES (313,'Law','Litigation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (314,'Law','Medical Professional Liability');
INSERT INTO categories (id,maincategory,subcategory) VALUES (315,'Law','Military');
INSERT INTO categories (id,maincategory,subcategory) VALUES (316,'Law','National Security');
INSERT INTO categories (id,maincategory,subcategory) VALUES (317,'Law','Personal Injury');
INSERT INTO categories (id,maincategory,subcategory) VALUES (318,'Law','Privacy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (319,'Law','Property');
INSERT INTO categories (id,maincategory,subcategory) VALUES (320,'Law','Public Defense');
INSERT INTO categories (id,maincategory,subcategory) VALUES (321,'Law','Real Estate');
INSERT INTO categories (id,maincategory,subcategory) VALUES (322,'Law','Securities');
INSERT INTO categories (id,maincategory,subcategory) VALUES (323,'Law','Social Security Disability');
INSERT INTO categories (id,maincategory,subcategory) VALUES (324,'Law','Sports');
INSERT INTO categories (id,maincategory,subcategory) VALUES (325,'Law','Taxation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (326,'Law','Workers Compensation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (327,'Medical','Aerospace Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (328,'Medical','Allergy and Immunology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (329,'Medical','Anesthesiology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (330,'Medical','Child Neurology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (331,'Medical','Clinical Biochemical Genetics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (332,'Medical','Clinical Cytogenetics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (333,'Medical','Clinical Genetics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (334,'Medical','Clinical Molecular Genetics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (335,'Medical','CME');
INSERT INTO categories (id,maincategory,subcategory) VALUES (336,'Medical','Colon and Rectal Surgery');
INSERT INTO categories (id,maincategory,subcategory) VALUES (337,'Medical','Continuing Medical Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (338,'Medical','Dermatology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (339,'Medical','Diagnostic Radiology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (340,'Medical','Emergency Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (341,'Medical','Family Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (342,'Medical','Internal Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (343,'Medical','Medical Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (344,'Medical','Medical Physics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (345,'Medical','Neurological Surgery');
INSERT INTO categories (id,maincategory,subcategory) VALUES (346,'Medical','Neurology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (347,'Medical','Nuclear Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (348,'Medical','Obstetrics and Gynecology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (349,'Medical','Occupational Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (350,'Medical','Oncology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (351,'Medical','Otolaryngology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (352,'Medical','Pathology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (353,'Medical','Pediatrics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (354,'Medical','Physical Medicine and Rehabilitation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (355,'Medical','Plastic Surgery');
INSERT INTO categories (id,maincategory,subcategory) VALUES (356,'Medical','Psychiatry');
INSERT INTO categories (id,maincategory,subcategory) VALUES (357,'Medical','Public Health and General Preventive Medicine');
INSERT INTO categories (id,maincategory,subcategory) VALUES (358,'Medical','Radiation Oncology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (359,'Medical','Surgery');
INSERT INTO categories (id,maincategory,subcategory) VALUES (360,'Medical','Thoracic and Cardiac Surgery');
INSERT INTO categories (id,maincategory,subcategory) VALUES (361,'Medical','Urology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (362,'Medical','Vascular Surgery');
INSERT INTO categories (id,maincategory,subcategory) VALUES (363,'News','Colleges and Universities');
INSERT INTO categories (id,maincategory,subcategory) VALUES (364,'News','Current Events');
INSERT INTO categories (id,maincategory,subcategory) VALUES (365,'News','Internet');
INSERT INTO categories (id,maincategory,subcategory) VALUES (366,'News','Magazines');
INSERT INTO categories (id,maincategory,subcategory) VALUES (367,'News','Media');
INSERT INTO categories (id,maincategory,subcategory) VALUES (368,'News','Newspapers');
INSERT INTO categories (id,maincategory,subcategory) VALUES (369,'News','Photojournalism');
INSERT INTO categories (id,maincategory,subcategory) VALUES (370,'News','Radio');
INSERT INTO categories (id,maincategory,subcategory) VALUES (371,'News','Television');
INSERT INTO categories (id,maincategory,subcategory) VALUES (372,'News','Weather');
INSERT INTO categories (id,maincategory,subcategory) VALUES (373,'Nursing','Addictions Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (374,'Nursing','Agency Nurses');
INSERT INTO categories (id,maincategory,subcategory) VALUES (375,'Nursing','Ambulatory Care Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (376,'Nursing','Burn Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (377,'Nursing','Camp Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (378,'Nursing','Cardiac Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (379,'Nursing','Case Management Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (380,'Nursing','Clinic Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (381,'Nursing','Community Health Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (382,'Nursing','Continence');
INSERT INTO categories (id,maincategory,subcategory) VALUES (383,'Nursing','Correctional Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (384,'Nursing','Developmental Disabilities');
INSERT INTO categories (id,maincategory,subcategory) VALUES (385,'Nursing','Diabetes');
INSERT INTO categories (id,maincategory,subcategory) VALUES (386,'Nursing','Dialysis');
INSERT INTO categories (id,maincategory,subcategory) VALUES (387,'Nursing','Directors Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (388,'Nursing','Emergency Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (389,'Nursing','Endocrine Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (390,'Nursing','Entrepreneurs in Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (391,'Nursing','Flight Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (392,'Nursing','Forensic Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (393,'Nursing','Gastroenterology Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (394,'Nursing','Geriatric Nurses');
INSERT INTO categories (id,maincategory,subcategory) VALUES (395,'Nursing','Government Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (396,'Nursing','Government Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (397,'Nursing','Holistic Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (398,'Nursing','Home Health Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (399,'Nursing','Hospice Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (400,'Nursing','Hyperbaric Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (401,'Nursing','Infectious Disease Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (402,'Nursing','Infusion Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (403,'Nursing','LTC Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (404,'Nursing','MDS Coordinator Information');
INSERT INTO categories (id,maincategory,subcategory) VALUES (405,'Nursing','Medical-Surgical Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (406,'Nursing','Military Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (407,'Nursing','Neurological Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (408,'Nursing','Nurse Massage Therapists');
INSERT INTO categories (id,maincategory,subcategory) VALUES (409,'Nursing','Nurse Staff Development');
INSERT INTO categories (id,maincategory,subcategory) VALUES (410,'Nursing','Nursing Educators');
INSERT INTO categories (id,maincategory,subcategory) VALUES (411,'Nursing','Nursing Faculty');
INSERT INTO categories (id,maincategory,subcategory) VALUES (412,'Nursing','Nursing Informatics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (413,'Nursing','Nursing Management');
INSERT INTO categories (id,maincategory,subcategory) VALUES (414,'Nursing','Ob-Gyn Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (415,'Nursing','Occupational Health Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (416,'Nursing','Oncology Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (417,'Nursing','Operating Room Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (418,'Nursing','Orthopaedic Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (419,'Nursing','Ostomy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (420,'Nursing','PACU Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (421,'Nursing','Pain Management Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (422,'Nursing','Parish Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (423,'Nursing','Pediatric Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (424,'Nursing','Private Duty Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (425,'Nursing','Psychiatric Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (426,'Nursing','Public Health Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (427,'Nursing','Pulmonary Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (428,'Nursing','Quality Improvement');
INSERT INTO categories (id,maincategory,subcategory) VALUES (429,'Nursing','Radiology Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (430,'Nursing','Rehabilitation Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (431,'Nursing','Renal');
INSERT INTO categories (id,maincategory,subcategory) VALUES (432,'Nursing','Research Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (433,'Nursing','Rural Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (434,'Nursing','School Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (435,'Nursing','Surface Transport Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (436,'Nursing','Telephone Triage Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (437,'Nursing','Travel Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (438,'Nursing','Urology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (439,'Nursing','Volunteer Nursing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (440,'Nursing','Wound');
INSERT INTO categories (id,maincategory,subcategory) VALUES (441,'Recreation','Antiques');
INSERT INTO categories (id,maincategory,subcategory) VALUES (442,'Recreation','Audio');
INSERT INTO categories (id,maincategory,subcategory) VALUES (443,'Recreation','Autos');
INSERT INTO categories (id,maincategory,subcategory) VALUES (444,'Recreation','Aviation');
INSERT INTO categories (id,maincategory,subcategory) VALUES (445,'Recreation','Birding');
INSERT INTO categories (id,maincategory,subcategory) VALUES (446,'Recreation','Boating');
INSERT INTO categories (id,maincategory,subcategory) VALUES (447,'Recreation','Camps');
INSERT INTO categories (id,maincategory,subcategory) VALUES (448,'Recreation','Climbing');
INSERT INTO categories (id,maincategory,subcategory) VALUES (449,'Recreation','Collecting');
INSERT INTO categories (id,maincategory,subcategory) VALUES (450,'Recreation','Drugs');
INSERT INTO categories (id,maincategory,subcategory) VALUES (451,'Recreation','Games');
INSERT INTO categories (id,maincategory,subcategory) VALUES (452,'Recreation','Gardens');
INSERT INTO categories (id,maincategory,subcategory) VALUES (453,'Recreation','Guns');
INSERT INTO categories (id,maincategory,subcategory) VALUES (454,'Recreation','Humor');
INSERT INTO categories (id,maincategory,subcategory) VALUES (455,'Recreation','Kites');
INSERT INTO categories (id,maincategory,subcategory) VALUES (456,'Recreation','Knives');
INSERT INTO categories (id,maincategory,subcategory) VALUES (457,'Recreation','Living History');
INSERT INTO categories (id,maincategory,subcategory) VALUES (458,'Recreation','Locks');
INSERT INTO categories (id,maincategory,subcategory) VALUES (459,'Recreation','Models');
INSERT INTO categories (id,maincategory,subcategory) VALUES (460,'Recreation','Motorcycles');
INSERT INTO categories (id,maincategory,subcategory) VALUES (461,'Recreation','Nu');
INSERT INTO categories (id,maincategory,subcategory) VALUES (462,'Recreation','Outdoors');
INSERT INTO categories (id,maincategory,subcategory) VALUES (463,'Recreation','Parties');
INSERT INTO categories (id,maincategory,subcategory) VALUES (464,'Recreation','Pets');
INSERT INTO categories (id,maincategory,subcategory) VALUES (465,'Recreation','Picture Ratings');
INSERT INTO categories (id,maincategory,subcategory) VALUES (466,'Recreation','Radio');
INSERT INTO categories (id,maincategory,subcategory) VALUES (467,'Recreation','Roads and Highways');
INSERT INTO categories (id,maincategory,subcategory) VALUES (468,'Recreation','Scouting');
INSERT INTO categories (id,maincategory,subcategory) VALUES (469,'Recreation','Shopping');
INSERT INTO categories (id,maincategory,subcategory) VALUES (470,'Recreation','Smoking');
INSERT INTO categories (id,maincategory,subcategory) VALUES (471,'Recreation','Sports');
INSERT INTO categories (id,maincategory,subcategory) VALUES (472,'Recreation','Theme Parks');
INSERT INTO categories (id,maincategory,subcategory) VALUES (473,'Recreation','Tobacco');
INSERT INTO categories (id,maincategory,subcategory) VALUES (474,'Recreation','Trains and Railroads');
INSERT INTO categories (id,maincategory,subcategory) VALUES (475,'Recreation','Travel');
INSERT INTO categories (id,maincategory,subcategory) VALUES (476,'Reference','Almanacs');
INSERT INTO categories (id,maincategory,subcategory) VALUES (477,'Reference','Archives');
INSERT INTO categories (id,maincategory,subcategory) VALUES (478,'Reference','Ask an Expert');
INSERT INTO categories (id,maincategory,subcategory) VALUES (479,'Reference','Bibliography');
INSERT INTO categories (id,maincategory,subcategory) VALUES (480,'Reference','Biography');
INSERT INTO categories (id,maincategory,subcategory) VALUES (481,'Reference','Books');
INSERT INTO categories (id,maincategory,subcategory) VALUES (482,'Reference','Dictionaries');
INSERT INTO categories (id,maincategory,subcategory) VALUES (483,'Reference','Directories');
INSERT INTO categories (id,maincategory,subcategory) VALUES (484,'Reference','Education');
INSERT INTO categories (id,maincategory,subcategory) VALUES (485,'Reference','Encyclopedias');
INSERT INTO categories (id,maincategory,subcategory) VALUES (486,'Reference','Flags');
INSERT INTO categories (id,maincategory,subcategory) VALUES (487,'Reference','Geography');
INSERT INTO categories (id,maincategory,subcategory) VALUES (488,'Reference','Knots');
INSERT INTO categories (id,maincategory,subcategory) VALUES (489,'Reference','Knowledge Management');
INSERT INTO categories (id,maincategory,subcategory) VALUES (490,'Reference','Libraries');
INSERT INTO categories (id,maincategory,subcategory) VALUES (491,'Reference','Museums');
INSERT INTO categories (id,maincategory,subcategory) VALUES (492,'Reference','Parliamentary Procedure');
INSERT INTO categories (id,maincategory,subcategory) VALUES (493,'Reference','Quotations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (494,'Reference','Thesauri');
INSERT INTO categories (id,maincategory,subcategory) VALUES (495,'Reference','Time');
INSERT INTO categories (id,maincategory,subcategory) VALUES (496,'Science','Aeronautics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (497,'Science','Agriculture');
INSERT INTO categories (id,maincategory,subcategory) VALUES (498,'Science','Alternative');
INSERT INTO categories (id,maincategory,subcategory) VALUES (499,'Science','Anomalies and Alternative Science');
INSERT INTO categories (id,maincategory,subcategory) VALUES (500,'Science','Astronomy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (501,'Science','Biochemistry');
INSERT INTO categories (id,maincategory,subcategory) VALUES (502,'Science','Biology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (503,'Science','Biotechnology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (504,'Science','Chemistry');
INSERT INTO categories (id,maincategory,subcategory) VALUES (505,'Science','Civil');
INSERT INTO categories (id,maincategory,subcategory) VALUES (506,'Science','Earth Science');
INSERT INTO categories (id,maincategory,subcategory) VALUES (507,'Science','Earth Sciences');
INSERT INTO categories (id,maincategory,subcategory) VALUES (508,'Science','Ecology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (509,'Science','Educational Resources');
INSERT INTO categories (id,maincategory,subcategory) VALUES (510,'Science','Electronics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (511,'Science','Employment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (512,'Science','Energy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (513,'Science','Engineering');
INSERT INTO categories (id,maincategory,subcategory) VALUES (514,'Science','Environment');
INSERT INTO categories (id,maincategory,subcategory) VALUES (515,'Science','Forensics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (516,'Science','Forestry');
INSERT INTO categories (id,maincategory,subcategory) VALUES (517,'Science','Geography');
INSERT INTO categories (id,maincategory,subcategory) VALUES (518,'Science','Geology and Geophysics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (519,'Science','Information Technology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (520,'Science','Instruments and Supplies');
INSERT INTO categories (id,maincategory,subcategory) VALUES (521,'Science','Life Sciences');
INSERT INTO categories (id,maincategory,subcategory) VALUES (522,'Science','Mathematics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (523,'Science','Mechanical');
INSERT INTO categories (id,maincategory,subcategory) VALUES (524,'Science','Meteorology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (525,'Science','Methods and Techniques');
INSERT INTO categories (id,maincategory,subcategory) VALUES (526,'Science','Nanotechnology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (527,'Science','Oceanography');
INSERT INTO categories (id,maincategory,subcategory) VALUES (528,'Science','Organizations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (529,'Science','Paleontology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (530,'Science','Physics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (531,'Science','Policy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (532,'Science','Psychology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (533,'Science','Reference');
INSERT INTO categories (id,maincategory,subcategory) VALUES (534,'Science','Research');
INSERT INTO categories (id,maincategory,subcategory) VALUES (535,'Science','Science in Society');
INSERT INTO categories (id,maincategory,subcategory) VALUES (536,'Science','Social Sciences');
INSERT INTO categories (id,maincategory,subcategory) VALUES (537,'Science','Space');
INSERT INTO categories (id,maincategory,subcategory) VALUES (538,'Science','Sports');
INSERT INTO categories (id,maincategory,subcategory) VALUES (539,'Science','Technology');
INSERT INTO categories (id,maincategory,subcategory) VALUES (540,'Science','Vibrations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (541,'Science','Visual Languages');
INSERT INTO categories (id,maincategory,subcategory) VALUES (542,'Science','Wireless');
INSERT INTO categories (id,maincategory,subcategory) VALUES (543,'Society','Activism');
INSERT INTO categories (id,maincategory,subcategory) VALUES (544,'Society','Advice');
INSERT INTO categories (id,maincategory,subcategory) VALUES (545,'Society','Crime');
INSERT INTO categories (id,maincategory,subcategory) VALUES (546,'Society','Death');
INSERT INTO categories (id,maincategory,subcategory) VALUES (547,'Society','Disabled');
INSERT INTO categories (id,maincategory,subcategory) VALUES (548,'Society','Ethnicity');
INSERT INTO categories (id,maincategory,subcategory) VALUES (549,'Society','Families');
INSERT INTO categories (id,maincategory,subcategory) VALUES (550,'Society','Fashion');
INSERT INTO categories (id,maincategory,subcategory) VALUES (551,'Society','Firearms');
INSERT INTO categories (id,maincategory,subcategory) VALUES (552,'Society','Folklore');
INSERT INTO categories (id,maincategory,subcategory) VALUES (553,'Society','Future');
INSERT INTO categories (id,maincategory,subcategory) VALUES (554,'Society','Gay');
INSERT INTO categories (id,maincategory,subcategory) VALUES (555,'Society','Gay, Lesbian, and Bisexual');
INSERT INTO categories (id,maincategory,subcategory) VALUES (556,'Society','Genealogy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (557,'Society','Government');
INSERT INTO categories (id,maincategory,subcategory) VALUES (558,'Society','History');
INSERT INTO categories (id,maincategory,subcategory) VALUES (559,'Society','Holidays');
INSERT INTO categories (id,maincategory,subcategory) VALUES (560,'Society','Issues');
INSERT INTO categories (id,maincategory,subcategory) VALUES (561,'Society','Law');
INSERT INTO categories (id,maincategory,subcategory) VALUES (562,'Society','Lifestyle Choices');
INSERT INTO categories (id,maincategory,subcategory) VALUES (563,'Society','Men');
INSERT INTO categories (id,maincategory,subcategory) VALUES (564,'Society','Military');
INSERT INTO categories (id,maincategory,subcategory) VALUES (565,'Society','Mythology and Folklore');
INSERT INTO categories (id,maincategory,subcategory) VALUES (566,'Society','Organizations');
INSERT INTO categories (id,maincategory,subcategory) VALUES (567,'Society','Paranormal');
INSERT INTO categories (id,maincategory,subcategory) VALUES (568,'Society','Philanthropy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (569,'Society','Philosophy');
INSERT INTO categories (id,maincategory,subcategory) VALUES (570,'Society','Politics');
INSERT INTO categories (id,maincategory,subcategory) VALUES (571,'Society','Relationships');
INSERT INTO categories (id,maincategory,subcategory) VALUES (572,'Society','Religion and Spirituality');
INSERT INTO categories (id,maincategory,subcategory) VALUES (573,'Society','Sexuality');
INSERT INTO categories (id,maincategory,subcategory) VALUES (574,'Society','Subcultures');
INSERT INTO categories (id,maincategory,subcategory) VALUES (575,'Society','Transgendered');
INSERT INTO categories (id,maincategory,subcategory) VALUES (576,'Society','Weddings');
INSERT INTO categories (id,maincategory,subcategory) VALUES (577,'Society','Women');
INSERT INTO categories (id,maincategory,subcategory) VALUES (578,'Society','Work');

COMMIT;