INSERT INTO countries (id,countrycode,countryname) VALUES (1,'AF','Afghanistan');
INSERT INTO countries (id,countrycode,countryname) VALUES (2,'AL','Albania');
INSERT INTO countries (id,countrycode,countryname) VALUES (3,'DZ','Algeria');
INSERT INTO countries (id,countrycode,countryname) VALUES (4,'AS','American Samoa');
INSERT INTO countries (id,countrycode,countryname) VALUES (5,'AD','Andorra');
INSERT INTO countries (id,countrycode,countryname) VALUES (6,'AO','Angola');
INSERT INTO countries (id,countrycode,countryname) VALUES (7,'AI','Anguilla');
INSERT INTO countries (id,countrycode,countryname) VALUES (8,'AG','Antigua And Barbuda');
INSERT INTO countries (id,countrycode,countryname) VALUES (9,'AR','Argentina');
INSERT INTO countries (id,countrycode,countryname) VALUES (10,'AM','Armenia');
INSERT INTO countries (id,countrycode,countryname) VALUES (11,'AW','Aruba');
INSERT INTO countries (id,countrycode,countryname) VALUES (12,'AU','Australia');
INSERT INTO countries (id,countrycode,countryname) VALUES (13,'AT','Austria');
INSERT INTO countries (id,countrycode,countryname) VALUES (14,'AZ','Azerbaijan');
INSERT INTO countries (id,countrycode,countryname) VALUES (15,'AX','Åland Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (16,'BS','Bahamas');
INSERT INTO countries (id,countrycode,countryname) VALUES (17,'BH','Bahrain');
INSERT INTO countries (id,countrycode,countryname) VALUES (18,'BD','Bangladesh');
INSERT INTO countries (id,countrycode,countryname) VALUES (19,'BB','Barbados');
INSERT INTO countries (id,countrycode,countryname) VALUES (20,'BY','Belarus');
INSERT INTO countries (id,countrycode,countryname) VALUES (21,'BE','Belgium');
INSERT INTO countries (id,countrycode,countryname) VALUES (22,'BZ','Belize');
INSERT INTO countries (id,countrycode,countryname) VALUES (23,'BJ','Benin');
INSERT INTO countries (id,countrycode,countryname) VALUES (24,'BM','Bermuda');
INSERT INTO countries (id,countrycode,countryname) VALUES (25,'BT','Bhutan');
INSERT INTO countries (id,countrycode,countryname) VALUES (26,'BO','Bolivia, Plurinational State Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (27,'BQ','Bonaire, Sint Eustatius And Saba');
INSERT INTO countries (id,countrycode,countryname) VALUES (28,'BA','Bosnia And Herzegovina');
INSERT INTO countries (id,countrycode,countryname) VALUES (29,'BW','Botswana');
INSERT INTO countries (id,countrycode,countryname) VALUES (30,'BR','Brazil');
INSERT INTO countries (id,countrycode,countryname) VALUES (31,'BN','Brunei Darussalam');
INSERT INTO countries (id,countrycode,countryname) VALUES (32,'BG','Bulgaria');
INSERT INTO countries (id,countrycode,countryname) VALUES (33,'BF','Burkina Faso');
INSERT INTO countries (id,countrycode,countryname) VALUES (34,'BI','Burundi');
INSERT INTO countries (id,countrycode,countryname) VALUES (35,'KH','Cambodia');
INSERT INTO countries (id,countrycode,countryname) VALUES (36,'CM','Cameroon');
INSERT INTO countries (id,countrycode,countryname) VALUES (37,'CA','Canada');
INSERT INTO countries (id,countrycode,countryname) VALUES (38,'CV','Cape Verde');
INSERT INTO countries (id,countrycode,countryname) VALUES (39,'KY','Cayman Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (40,'CF','Central African Republic');
INSERT INTO countries (id,countrycode,countryname) VALUES (41,'TD','Chad');
INSERT INTO countries (id,countrycode,countryname) VALUES (42,'CL','Chile');
INSERT INTO countries (id,countrycode,countryname) VALUES (43,'CN','China');
INSERT INTO countries (id,countrycode,countryname) VALUES (44,'CO','Colombia');
INSERT INTO countries (id,countrycode,countryname) VALUES (45,'KM','Comoros');
INSERT INTO countries (id,countrycode,countryname) VALUES (46,'CG','Congo');
INSERT INTO countries (id,countrycode,countryname) VALUES (47,'CD','Congo, The Democratic Republic Of The');
INSERT INTO countries (id,countrycode,countryname) VALUES (48,'CK','Cook Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (49,'CR','Costa Rica');
INSERT INTO countries (id,countrycode,countryname) VALUES (50,'CI','Côte D''Ivoire');
INSERT INTO countries (id,countrycode,countryname) VALUES (51,'HR','Croatia');
INSERT INTO countries (id,countrycode,countryname) VALUES (52,'CU','Cuba');
INSERT INTO countries (id,countrycode,countryname) VALUES (53,'CW','Curaçao');
INSERT INTO countries (id,countrycode,countryname) VALUES (54,'CY','Cyprus');
INSERT INTO countries (id,countrycode,countryname) VALUES (55,'CZ','Czech Republic');
INSERT INTO countries (id,countrycode,countryname) VALUES (56,'DK','Denmark');
INSERT INTO countries (id,countrycode,countryname) VALUES (57,'DJ','Djibouti');
INSERT INTO countries (id,countrycode,countryname) VALUES (58,'DM','Dominica');
INSERT INTO countries (id,countrycode,countryname) VALUES (59,'DO','Dominican Republic');
INSERT INTO countries (id,countrycode,countryname) VALUES (60,'EC','Ecuador');
INSERT INTO countries (id,countrycode,countryname) VALUES (61,'EG','Egypt');
INSERT INTO countries (id,countrycode,countryname) VALUES (62,'SV','El Salvador');
INSERT INTO countries (id,countrycode,countryname) VALUES (63,'GQ','Equatorial Guinea');
INSERT INTO countries (id,countrycode,countryname) VALUES (64,'ER','Eritrea');
INSERT INTO countries (id,countrycode,countryname) VALUES (65,'EE','Estonia');
INSERT INTO countries (id,countrycode,countryname) VALUES (66,'ET','Ethiopia');
INSERT INTO countries (id,countrycode,countryname) VALUES (67,'FK','Falkland Islands (Malvinas)');
INSERT INTO countries (id,countrycode,countryname) VALUES (68,'FO','Faroe Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (69,'FJ','Fiji');
INSERT INTO countries (id,countrycode,countryname) VALUES (70,'FI','Finland');
INSERT INTO countries (id,countrycode,countryname) VALUES (71,'FR','France');
INSERT INTO countries (id,countrycode,countryname) VALUES (72,'GF','French Guiana');
INSERT INTO countries (id,countrycode,countryname) VALUES (73,'PF','French Polynesia');
INSERT INTO countries (id,countrycode,countryname) VALUES (74,'GA','Gabon');
INSERT INTO countries (id,countrycode,countryname) VALUES (75,'GM','Gambia');
INSERT INTO countries (id,countrycode,countryname) VALUES (76,'GE','Georgia');
INSERT INTO countries (id,countrycode,countryname) VALUES (77,'DE','Germany');
INSERT INTO countries (id,countrycode,countryname) VALUES (78,'GH','Ghana');
INSERT INTO countries (id,countrycode,countryname) VALUES (79,'GI','Gibraltar');
INSERT INTO countries (id,countrycode,countryname) VALUES (80,'GR','Greece');
INSERT INTO countries (id,countrycode,countryname) VALUES (81,'GL','Greenland');
INSERT INTO countries (id,countrycode,countryname) VALUES (82,'GD','Grenada');
INSERT INTO countries (id,countrycode,countryname) VALUES (83,'GP','Guadeloupe');
INSERT INTO countries (id,countrycode,countryname) VALUES (84,'GU','Guam');
INSERT INTO countries (id,countrycode,countryname) VALUES (85,'GT','Guatemala');
INSERT INTO countries (id,countrycode,countryname) VALUES (86,'GN','Guinea');
INSERT INTO countries (id,countrycode,countryname) VALUES (87,'GW','Guinea-Bissau');
INSERT INTO countries (id,countrycode,countryname) VALUES (88,'GY','Guyana');
INSERT INTO countries (id,countrycode,countryname) VALUES (89,'HT','Haiti');
INSERT INTO countries (id,countrycode,countryname) VALUES (90,'VA','Holy See (Vatican City State)');
INSERT INTO countries (id,countrycode,countryname) VALUES (91,'HN','Honduras');
INSERT INTO countries (id,countrycode,countryname) VALUES (92,'HK','Hong Kong');
INSERT INTO countries (id,countrycode,countryname) VALUES (93,'HU','Hungary');
INSERT INTO countries (id,countrycode,countryname) VALUES (94,'IS','Iceland');
INSERT INTO countries (id,countrycode,countryname) VALUES (95,'IN','India');
INSERT INTO countries (id,countrycode,countryname) VALUES (96,'ID','Indonesia');
INSERT INTO countries (id,countrycode,countryname) VALUES (97,'IR','Iran, Islamic Republic Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (98,'IQ','Iraq');
INSERT INTO countries (id,countrycode,countryname) VALUES (99,'IE','Ireland');
INSERT INTO countries (id,countrycode,countryname) VALUES (100,'IM','Isle Of Man');
INSERT INTO countries (id,countrycode,countryname) VALUES (101,'IL','Israel');
INSERT INTO countries (id,countrycode,countryname) VALUES (102,'IT','Italy');
INSERT INTO countries (id,countrycode,countryname) VALUES (103,'JM','Jamaica');
INSERT INTO countries (id,countrycode,countryname) VALUES (104,'JP','Japan');
INSERT INTO countries (id,countrycode,countryname) VALUES (105,'JE','Jersey');
INSERT INTO countries (id,countrycode,countryname) VALUES (106,'JO','Jordan');
INSERT INTO countries (id,countrycode,countryname) VALUES (107,'KZ','Kazakhstan');
INSERT INTO countries (id,countrycode,countryname) VALUES (108,'KE','Kenya');
INSERT INTO countries (id,countrycode,countryname) VALUES (109,'KI','Kiribati');
INSERT INTO countries (id,countrycode,countryname) VALUES (110,'KR','Korea, Republic Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (111,'KW','Kuwait');
INSERT INTO countries (id,countrycode,countryname) VALUES (112,'KG','Kyrgyzstan');
INSERT INTO countries (id,countrycode,countryname) VALUES (113,'LA','Lao People''S Democratic Republic');
INSERT INTO countries (id,countrycode,countryname) VALUES (114,'LV','Latvia');
INSERT INTO countries (id,countrycode,countryname) VALUES (115,'LB','Lebanon');
INSERT INTO countries (id,countrycode,countryname) VALUES (116,'LS','Lesotho');
INSERT INTO countries (id,countrycode,countryname) VALUES (117,'LR','Liberia');
INSERT INTO countries (id,countrycode,countryname) VALUES (118,'LY','Libya');
INSERT INTO countries (id,countrycode,countryname) VALUES (119,'LI','Liechtenstein');
INSERT INTO countries (id,countrycode,countryname) VALUES (120,'LT','Lithuania');
INSERT INTO countries (id,countrycode,countryname) VALUES (121,'LU','Luxembourg');
INSERT INTO countries (id,countrycode,countryname) VALUES (122,'MO','Macao');
INSERT INTO countries (id,countrycode,countryname) VALUES (123,'MK','Macedonia, The Former Yugoslav Republic Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (124,'MG','Madagascar');
INSERT INTO countries (id,countrycode,countryname) VALUES (125,'MW','Malawi');
INSERT INTO countries (id,countrycode,countryname) VALUES (126,'MY','Malaysia');
INSERT INTO countries (id,countrycode,countryname) VALUES (127,'MV','Maldives');
INSERT INTO countries (id,countrycode,countryname) VALUES (128,'ML','Mali');
INSERT INTO countries (id,countrycode,countryname) VALUES (129,'MT','Malta');
INSERT INTO countries (id,countrycode,countryname) VALUES (130,'MH','Marshall Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (131,'MQ','Martinique');
INSERT INTO countries (id,countrycode,countryname) VALUES (132,'MR','Mauritania');
INSERT INTO countries (id,countrycode,countryname) VALUES (133,'MU','Mauritius');
INSERT INTO countries (id,countrycode,countryname) VALUES (134,'YT','Mayotte');
INSERT INTO countries (id,countrycode,countryname) VALUES (135,'MX','Mexico');
INSERT INTO countries (id,countrycode,countryname) VALUES (136,'FM','Micronesia, Federated States Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (137,'MD','Moldova, Republic Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (138,'MC','Monaco');
INSERT INTO countries (id,countrycode,countryname) VALUES (139,'MN','Mongolia');
INSERT INTO countries (id,countrycode,countryname) VALUES (140,'ME','Montenegro');
INSERT INTO countries (id,countrycode,countryname) VALUES (141,'MS','Montserrat');
INSERT INTO countries (id,countrycode,countryname) VALUES (142,'MA','Morocco');
INSERT INTO countries (id,countrycode,countryname) VALUES (143,'MZ','Mozambique');
INSERT INTO countries (id,countrycode,countryname) VALUES (144,'MM','Myanmar');
INSERT INTO countries (id,countrycode,countryname) VALUES (145,'NA','Namibia');
INSERT INTO countries (id,countrycode,countryname) VALUES (146,'NR','Nauru');
INSERT INTO countries (id,countrycode,countryname) VALUES (147,'NP','Nepal');
INSERT INTO countries (id,countrycode,countryname) VALUES (148,'NL','Netherlands');
INSERT INTO countries (id,countrycode,countryname) VALUES (149,'AN','Netherlands Antilles');
INSERT INTO countries (id,countrycode,countryname) VALUES (150,'NC','New Caledonia');
INSERT INTO countries (id,countrycode,countryname) VALUES (151,'NZ','New Zealand');
INSERT INTO countries (id,countrycode,countryname) VALUES (152,'NI','Nicaragua');
INSERT INTO countries (id,countrycode,countryname) VALUES (153,'NE','Niger');
INSERT INTO countries (id,countrycode,countryname) VALUES (154,'NG','Nigeria');
INSERT INTO countries (id,countrycode,countryname) VALUES (155,'NU','Niue');
INSERT INTO countries (id,countrycode,countryname) VALUES (156,'MP','Northern Mariana Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (157,'NO','Norway');
INSERT INTO countries (id,countrycode,countryname) VALUES (158,'OM','Oman');
INSERT INTO countries (id,countrycode,countryname) VALUES (159,'PK','Pakistan');
INSERT INTO countries (id,countrycode,countryname) VALUES (160,'PW','Palau');
INSERT INTO countries (id,countrycode,countryname) VALUES (161,'PS','Palestine, State Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (162,'PA','Panama');
INSERT INTO countries (id,countrycode,countryname) VALUES (163,'PG','Papua New Guinea');
INSERT INTO countries (id,countrycode,countryname) VALUES (164,'PY','Paraguay');
INSERT INTO countries (id,countrycode,countryname) VALUES (165,'PE','Peru');
INSERT INTO countries (id,countrycode,countryname) VALUES (166,'PH','Philippines');
INSERT INTO countries (id,countrycode,countryname) VALUES (167,'PL','Poland');
INSERT INTO countries (id,countrycode,countryname) VALUES (168,'PT','Portugal');
INSERT INTO countries (id,countrycode,countryname) VALUES (169,'PR','Puerto Rico');
INSERT INTO countries (id,countrycode,countryname) VALUES (170,'QA','Qatar');
INSERT INTO countries (id,countrycode,countryname) VALUES (171,'RE','Réunion');
INSERT INTO countries (id,countrycode,countryname) VALUES (172,'RO','Romania');
INSERT INTO countries (id,countrycode,countryname) VALUES (173,'RU','Russian Federation');
INSERT INTO countries (id,countrycode,countryname) VALUES (174,'RW','Rwanda');
INSERT INTO countries (id,countrycode,countryname) VALUES (175,'KN','Saint Kitts And Nevis');
INSERT INTO countries (id,countrycode,countryname) VALUES (176,'LC','Saint Lucia');
INSERT INTO countries (id,countrycode,countryname) VALUES (177,'MF','Saint Martin (French Part)');
INSERT INTO countries (id,countrycode,countryname) VALUES (178,'PM','Saint Pierre And Miquelon');
INSERT INTO countries (id,countrycode,countryname) VALUES (179,'VC','Saint Vincent And The Grenadines');
INSERT INTO countries (id,countrycode,countryname) VALUES (180,'WS','Samoa');
INSERT INTO countries (id,countrycode,countryname) VALUES (181,'SM','San Marino');
INSERT INTO countries (id,countrycode,countryname) VALUES (182,'ST','Sao Tome And Principe');
INSERT INTO countries (id,countrycode,countryname) VALUES (183,'SA','Saudi Arabia');
INSERT INTO countries (id,countrycode,countryname) VALUES (184,'SN','Senegal');
INSERT INTO countries (id,countrycode,countryname) VALUES (185,'RS','Serbia');
INSERT INTO countries (id,countrycode,countryname) VALUES (186,'SC','Seychelles');
INSERT INTO countries (id,countrycode,countryname) VALUES (187,'SL','Sierra Leone');
INSERT INTO countries (id,countrycode,countryname) VALUES (188,'SG','Singapore');
INSERT INTO countries (id,countrycode,countryname) VALUES (189,'SK','Slovakia');
INSERT INTO countries (id,countrycode,countryname) VALUES (190,'SI','Slovenia');
INSERT INTO countries (id,countrycode,countryname) VALUES (191,'SB','Solomon Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (192,'SO','Somalia');
INSERT INTO countries (id,countrycode,countryname) VALUES (193,'ZA','South Africa');
INSERT INTO countries (id,countrycode,countryname) VALUES (194,'SS','South Sudan');
INSERT INTO countries (id,countrycode,countryname) VALUES (195,'ES','Spain');
INSERT INTO countries (id,countrycode,countryname) VALUES (196,'LK','Sri Lanka');
INSERT INTO countries (id,countrycode,countryname) VALUES (197,'SD','Sudan');
INSERT INTO countries (id,countrycode,countryname) VALUES (198,'SR','Suriname');
INSERT INTO countries (id,countrycode,countryname) VALUES (199,'SZ','Swaziland');
INSERT INTO countries (id,countrycode,countryname) VALUES (200,'SE','Sweden');
INSERT INTO countries (id,countrycode,countryname) VALUES (201,'CH','Switzerland');
INSERT INTO countries (id,countrycode,countryname) VALUES (202,'SY','Syrian Arab Republic');
INSERT INTO countries (id,countrycode,countryname) VALUES (203,'TW','Taiwan, Province Of China');
INSERT INTO countries (id,countrycode,countryname) VALUES (204,'TJ','Tajikistan');
INSERT INTO countries (id,countrycode,countryname) VALUES (205,'TZ','Tanzania, United Republic Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (206,'TH','Thailand');
INSERT INTO countries (id,countrycode,countryname) VALUES (207,'TL','Timor-Leste');
INSERT INTO countries (id,countrycode,countryname) VALUES (208,'TG','Togo');
INSERT INTO countries (id,countrycode,countryname) VALUES (209,'TK','Tokelau');
INSERT INTO countries (id,countrycode,countryname) VALUES (210,'TO','Tonga');
INSERT INTO countries (id,countrycode,countryname) VALUES (211,'TT','Trinidad And Tobago');
INSERT INTO countries (id,countrycode,countryname) VALUES (212,'TN','Tunisia');
INSERT INTO countries (id,countrycode,countryname) VALUES (213,'TR','Turkey');
INSERT INTO countries (id,countrycode,countryname) VALUES (214,'TM','Turkmenistan');
INSERT INTO countries (id,countrycode,countryname) VALUES (215,'TC','Turks And Caicos Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (216,'UG','Uganda');
INSERT INTO countries (id,countrycode,countryname) VALUES (217,'UA','Ukraine');
INSERT INTO countries (id,countrycode,countryname) VALUES (218,'AE','United Arab Emirates');
INSERT INTO countries (id,countrycode,countryname) VALUES (219,'GB','United Kingdom');
INSERT INTO countries (id,countrycode,countryname) VALUES (220,'US','United States');
INSERT INTO countries (id,countrycode,countryname) VALUES (221,'UM','United States Minor Outlying Islands');
INSERT INTO countries (id,countrycode,countryname) VALUES (222,'UY','Uruguay');
INSERT INTO countries (id,countrycode,countryname) VALUES (223,'UZ','Uzbekistan');
INSERT INTO countries (id,countrycode,countryname) VALUES (224,'VU','Vanuatu');
INSERT INTO countries (id,countrycode,countryname) VALUES (225,'VE','Venezuela, Bolivarian Republic Of');
INSERT INTO countries (id,countrycode,countryname) VALUES (226,'VN','Viet Nam');
INSERT INTO countries (id,countrycode,countryname) VALUES (227,'VG','Virgin Islands, British');
INSERT INTO countries (id,countrycode,countryname) VALUES (228,'VI','Virgin Islands, U.S.');
INSERT INTO countries (id,countrycode,countryname) VALUES (229,'WF','Wallis And Futuna');
INSERT INTO countries (id,countrycode,countryname) VALUES (230,'YE','Yemen');
INSERT INTO countries (id,countrycode,countryname) VALUES (231,'ZM','Zambia');
INSERT INTO countries (id,countrycode,countryname) VALUES (232,'ZW','Zimbabwe');

COMMIT;