INSERT INTO cities (cityId,countryId,cityName) VALUES (1,5,'Andorra la Vella');
INSERT INTO cities (cityId,countryId,cityName) VALUES (2,218,'Abu Dhabi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (3,1,'Kabul');
INSERT INTO cities (cityId,countryId,cityName) VALUES (4,8,'Piggotts');
INSERT INTO cities (cityId,countryId,cityName) VALUES (5,7,'The Valley');
INSERT INTO cities (cityId,countryId,cityName) VALUES (6,2,'Durrës');
INSERT INTO cities (cityId,countryId,cityName) VALUES (7,10,'Abovyan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (8,149,'Kralendijk');
INSERT INTO cities (cityId,countryId,cityName) VALUES (9,6,'Luanda');
INSERT INTO cities (cityId,countryId,cityName) VALUES (10,9,'Abra Pampa');
INSERT INTO cities (cityId,countryId,cityName) VALUES (11,4,'Pago Pago');
INSERT INTO cities (cityId,countryId,cityName) VALUES (12,13,'Althofen');
INSERT INTO cities (cityId,countryId,cityName) VALUES (13,12,'Abbotsford');
INSERT INTO cities (cityId,countryId,cityName) VALUES (14,11,'Noord');
INSERT INTO cities (cityId,countryId,cityName) VALUES (15,15,'Mariehamn');
INSERT INTO cities (cityId,countryId,cityName) VALUES (16,14,'Baku');
INSERT INTO cities (cityId,countryId,cityName) VALUES (17,28,'Banja Luka');
INSERT INTO cities (cityId,countryId,cityName) VALUES (18,19,'Bridgetown');
INSERT INTO cities (cityId,countryId,cityName) VALUES (19,18,'Chittagong');
INSERT INTO cities (cityId,countryId,cityName) VALUES (20,21,'Aalst');
INSERT INTO cities (cityId,countryId,cityName) VALUES (21,33,'Ouagadougou');
INSERT INTO cities (cityId,countryId,cityName) VALUES (22,32,'Aksakovo');
INSERT INTO cities (cityId,countryId,cityName) VALUES (23,17,'A''ali');
INSERT INTO cities (cityId,countryId,cityName) VALUES (24,34,'Bujumbura');
INSERT INTO cities (cityId,countryId,cityName) VALUES (25,23,'Cotonou');
INSERT INTO cities (cityId,countryId,cityName) VALUES (26,24,'Hamilton');
INSERT INTO cities (cityId,countryId,cityName) VALUES (27,31,'Bandar Seri Begawan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (28,26,'Ayacucho');
INSERT INTO cities (cityId,countryId,cityName) VALUES (29,27,'Kralendijk');
INSERT INTO cities (cityId,countryId,cityName) VALUES (30,30,'Acaraú');
INSERT INTO cities (cityId,countryId,cityName) VALUES (31,16,'Adelaide Village');
INSERT INTO cities (cityId,countryId,cityName) VALUES (32,25,'Thimphu');
INSERT INTO cities (cityId,countryId,cityName) VALUES (33,29,'Gaborone');
INSERT INTO cities (cityId,countryId,cityName) VALUES (34,20,'Baranavichy');
INSERT INTO cities (cityId,countryId,cityName) VALUES (35,22,'Belize City');
INSERT INTO cities (cityId,countryId,cityName) VALUES (36,37,'Abbotsford');
INSERT INTO cities (cityId,countryId,cityName) VALUES (37,47,'Kinshasa');
INSERT INTO cities (cityId,countryId,cityName) VALUES (38,40,'Bangui');
INSERT INTO cities (cityId,countryId,cityName) VALUES (39,46,'Brazzaville');
INSERT INTO cities (cityId,countryId,cityName) VALUES (40,201,'Aadorf');
INSERT INTO cities (cityId,countryId,cityName) VALUES (41,50,'Abidjan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (42,48,'Nikao');
INSERT INTO cities (cityId,countryId,cityName) VALUES (43,42,'Alto Hospicio');
INSERT INTO cities (cityId,countryId,cityName) VALUES (44,36,'Bonabéri');
INSERT INTO cities (cityId,countryId,cityName) VALUES (45,43,'Aba');
INSERT INTO cities (cityId,countryId,cityName) VALUES (46,44,'Aguachica');
INSERT INTO cities (cityId,countryId,cityName) VALUES (47,49,'Alajuela');
INSERT INTO cities (cityId,countryId,cityName) VALUES (48,52,'Aguada de Pasajeros');
INSERT INTO cities (cityId,countryId,cityName) VALUES (49,38,'Praia');
INSERT INTO cities (cityId,countryId,cityName) VALUES (50,53,'Conroe');
INSERT INTO cities (cityId,countryId,cityName) VALUES (51,54,'Agios Dometios');
INSERT INTO cities (cityId,countryId,cityName) VALUES (52,55,'Adamov');
INSERT INTO cities (cityId,countryId,cityName) VALUES (53,77,'Aachen');
INSERT INTO cities (cityId,countryId,cityName) VALUES (54,57,'Djibouti');
INSERT INTO cities (cityId,countryId,cityName) VALUES (55,56,'Aabenraa');
INSERT INTO cities (cityId,countryId,cityName) VALUES (56,58,'Roseau');
INSERT INTO cities (cityId,countryId,cityName) VALUES (57,59,'Bavaro');
INSERT INTO cities (cityId,countryId,cityName) VALUES (58,3,'Alger');
INSERT INTO cities (cityId,countryId,cityName) VALUES (59,60,'Ambato');
INSERT INTO cities (cityId,countryId,cityName) VALUES (60,65,'Abja Parish');
INSERT INTO cities (cityId,countryId,cityName) VALUES (61,61,'Ad Doqi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (62,64,'Āsmara');
INSERT INTO cities (cityId,countryId,cityName) VALUES (63,195,'A Coruña');
INSERT INTO cities (cityId,countryId,cityName) VALUES (64,66,'Addis Ababa');
INSERT INTO cities (cityId,countryId,cityName) VALUES (65,70,'Äänekoski');
INSERT INTO cities (cityId,countryId,cityName) VALUES (66,69,'Nadi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (67,67,'Stanley');
INSERT INTO cities (cityId,countryId,cityName) VALUES (68,136,'Kolonia');
INSERT INTO cities (cityId,countryId,cityName) VALUES (69,68,'Torshavn');
INSERT INTO cities (cityId,countryId,cityName) VALUES (70,71,'Abbeville');
INSERT INTO cities (cityId,countryId,cityName) VALUES (71,74,'Kayes Congo');
INSERT INTO cities (cityId,countryId,cityName) VALUES (72,219,'Abbey Meads');
INSERT INTO cities (cityId,countryId,cityName) VALUES (73,82,'Bamboo');
INSERT INTO cities (cityId,countryId,cityName) VALUES (74,76,'Batumi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (75,72,'Cayenne');
INSERT INTO cities (cityId,countryId,cityName) VALUES (76,78,'Accra');
INSERT INTO cities (cityId,countryId,cityName) VALUES (77,79,'Gibraltar');
INSERT INTO cities (cityId,countryId,cityName) VALUES (78,81,'Nuuk');
INSERT INTO cities (cityId,countryId,cityName) VALUES (79,75,'Serrekunda');
INSERT INTO cities (cityId,countryId,cityName) VALUES (80,86,'Conakry');
INSERT INTO cities (cityId,countryId,cityName) VALUES (81,83,'Baie-Mahault');
INSERT INTO cities (cityId,countryId,cityName) VALUES (82,63,'Malabo');
INSERT INTO cities (cityId,countryId,cityName) VALUES (83,80,'Agia Paraskevi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (84,85,'Amatitlán');
INSERT INTO cities (cityId,countryId,cityName) VALUES (85,84,'Barrigada');
INSERT INTO cities (cityId,countryId,cityName) VALUES (86,87,'Bissau');
INSERT INTO cities (cityId,countryId,cityName) VALUES (87,88,'Georgetown');
INSERT INTO cities (cityId,countryId,cityName) VALUES (88,92,'Admiralty');
INSERT INTO cities (cityId,countryId,cityName) VALUES (89,91,'Comayagua');
INSERT INTO cities (cityId,countryId,cityName) VALUES (90,51,'Bjelovar');
INSERT INTO cities (cityId,countryId,cityName) VALUES (91,89,'Les Cayes');
INSERT INTO cities (cityId,countryId,cityName) VALUES (92,93,'1211 Budapest');
INSERT INTO cities (cityId,countryId,cityName) VALUES (93,96,'Balikpapan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (94,99,'Abbeyfeale');
INSERT INTO cities (cityId,countryId,cityName) VALUES (95,101,'Ashdod');
INSERT INTO cities (cityId,countryId,cityName) VALUES (96,100,'Douglas');
INSERT INTO cities (cityId,countryId,cityName) VALUES (97,95,'Agra');
INSERT INTO cities (cityId,countryId,cityName) VALUES (98,98,'Al Basrah');
INSERT INTO cities (cityId,countryId,cityName) VALUES (99,97,'Abadan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (100,94,'Akranes');
INSERT INTO cities (cityId,countryId,cityName) VALUES (101,102,'Aci Bonaccorsi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (102,105,'St Helier');
INSERT INTO cities (cityId,countryId,cityName) VALUES (103,103,'Kingston');
INSERT INTO cities (cityId,countryId,cityName) VALUES (104,106,'Amman');
INSERT INTO cities (cityId,countryId,cityName) VALUES (105,104,'Agano');
INSERT INTO cities (cityId,countryId,cityName) VALUES (106,108,'Mombasa');
INSERT INTO cities (cityId,countryId,cityName) VALUES (107,112,'Bishkek');
INSERT INTO cities (cityId,countryId,cityName) VALUES (108,35,'Phnom Penh');
INSERT INTO cities (cityId,countryId,cityName) VALUES (109,109,'Bairiki');
INSERT INTO cities (cityId,countryId,cityName) VALUES (110,45,'Vanadjou');
INSERT INTO cities (cityId,countryId,cityName) VALUES (111,175,'Basseterre');
INSERT INTO cities (cityId,countryId,cityName) VALUES (112,110,'Andong-si');
INSERT INTO cities (cityId,countryId,cityName) VALUES (113,111,'Al-Jahra');
INSERT INTO cities (cityId,countryId,cityName) VALUES (114,39,'George Town');
INSERT INTO cities (cityId,countryId,cityName) VALUES (115,107,'Abay');
INSERT INTO cities (cityId,countryId,cityName) VALUES (116,113,'Vientiane');
INSERT INTO cities (cityId,countryId,cityName) VALUES (117,115,'Antelias');
INSERT INTO cities (cityId,countryId,cityName) VALUES (118,176,'Castries');
INSERT INTO cities (cityId,countryId,cityName) VALUES (119,119,'Eschen');
INSERT INTO cities (cityId,countryId,cityName) VALUES (120,196,'Ambalangoda');
INSERT INTO cities (cityId,countryId,cityName) VALUES (121,117,'Monrovia');
INSERT INTO cities (cityId,countryId,cityName) VALUES (122,116,'Maseru');
INSERT INTO cities (cityId,countryId,cityName) VALUES (123,120,'Adomava');
INSERT INTO cities (cityId,countryId,cityName) VALUES (124,121,'Beckerich');
INSERT INTO cities (cityId,countryId,cityName) VALUES (125,114,'Cēsis');
INSERT INTO cities (cityId,countryId,cityName) VALUES (126,118,'Misrata');
INSERT INTO cities (cityId,countryId,cityName) VALUES (127,142,'Agadir');
INSERT INTO cities (cityId,countryId,cityName) VALUES (128,138,'Monaco');
INSERT INTO cities (cityId,countryId,cityName) VALUES (129,137,'Bender');
INSERT INTO cities (cityId,countryId,cityName) VALUES (130,140,'Podgorica');
INSERT INTO cities (cityId,countryId,cityName) VALUES (131,177,'Marigot');
INSERT INTO cities (cityId,countryId,cityName) VALUES (132,124,'Antananarivo');
INSERT INTO cities (cityId,countryId,cityName) VALUES (133,130,'Majuro');
INSERT INTO cities (cityId,countryId,cityName) VALUES (134,123,'Bitola');
INSERT INTO cities (cityId,countryId,cityName) VALUES (135,128,'Bamako');
INSERT INTO cities (cityId,countryId,cityName) VALUES (136,144,'Ka Lay');
INSERT INTO cities (cityId,countryId,cityName) VALUES (137,139,'Ulaanbaatar');
INSERT INTO cities (cityId,countryId,cityName) VALUES (138,122,'Macau');
INSERT INTO cities (cityId,countryId,cityName) VALUES (139,156,'Capitol Hill');
INSERT INTO cities (cityId,countryId,cityName) VALUES (140,131,'Fort-de-France');
INSERT INTO cities (cityId,countryId,cityName) VALUES (141,132,'Nouakchott');
INSERT INTO cities (cityId,countryId,cityName) VALUES (142,141,'Cudjoehead');
INSERT INTO cities (cityId,countryId,cityName) VALUES (143,129,'Attard');
INSERT INTO cities (cityId,countryId,cityName) VALUES (144,133,'Beau Bassin-Rose Hill');
INSERT INTO cities (cityId,countryId,cityName) VALUES (145,127,'Male');
INSERT INTO cities (cityId,countryId,cityName) VALUES (146,125,'Blantyre');
INSERT INTO cities (cityId,countryId,cityName) VALUES (147,135,'Acapulco');
INSERT INTO cities (cityId,countryId,cityName) VALUES (148,126,'Ampang');
INSERT INTO cities (cityId,countryId,cityName) VALUES (149,143,'Beira');
INSERT INTO cities (cityId,countryId,cityName) VALUES (150,145,'Gobabis');
INSERT INTO cities (cityId,countryId,cityName) VALUES (151,150,'Noumea');
INSERT INTO cities (cityId,countryId,cityName) VALUES (152,153,'Niamey');
INSERT INTO cities (cityId,countryId,cityName) VALUES (153,154,'Aba');
INSERT INTO cities (cityId,countryId,cityName) VALUES (154,152,'Corinto');
INSERT INTO cities (cityId,countryId,cityName) VALUES (155,148,'Aa en Hunze');
INSERT INTO cities (cityId,countryId,cityName) VALUES (156,157,'Ågotnes');
INSERT INTO cities (cityId,countryId,cityName) VALUES (157,147,'Kathmandu');
INSERT INTO cities (cityId,countryId,cityName) VALUES (158,146,'Arijejen');
INSERT INTO cities (cityId,countryId,cityName) VALUES (159,155,'Alofi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (160,151,'Albany');
INSERT INTO cities (cityId,countryId,cityName) VALUES (161,158,'Al Azaiba');
INSERT INTO cities (cityId,countryId,cityName) VALUES (162,162,'Bocas del Toro');
INSERT INTO cities (cityId,countryId,cityName) VALUES (163,165,'Abancay');
INSERT INTO cities (cityId,countryId,cityName) VALUES (164,73,'Papao');
INSERT INTO cities (cityId,countryId,cityName) VALUES (165,163,'Lae');
INSERT INTO cities (cityId,countryId,cityName) VALUES (166,166,'Alaminos');
INSERT INTO cities (cityId,countryId,cityName) VALUES (167,159,'Bannu');
INSERT INTO cities (cityId,countryId,cityName) VALUES (168,167,'Andrychów');
INSERT INTO cities (cityId,countryId,cityName) VALUES (169,178,'Saint-Pierre');
INSERT INTO cities (cityId,countryId,cityName) VALUES (170,169,'Aguadilla');
INSERT INTO cities (cityId,countryId,cityName) VALUES (171,161,'Jerusalem');
INSERT INTO cities (cityId,countryId,cityName) VALUES (172,168,'Abrantes Municipality');
INSERT INTO cities (cityId,countryId,cityName) VALUES (173,160,'Koror');
INSERT INTO cities (cityId,countryId,cityName) VALUES (174,164,'Asuncion');
INSERT INTO cities (cityId,countryId,cityName) VALUES (175,170,'Al Khawr');
INSERT INTO cities (cityId,countryId,cityName) VALUES (176,171,'Guadalupe');
INSERT INTO cities (cityId,countryId,cityName) VALUES (177,172,'Adjud');
INSERT INTO cities (cityId,countryId,cityName) VALUES (178,185,'Ada');
INSERT INTO cities (cityId,countryId,cityName) VALUES (179,173,'12 пос.');
INSERT INTO cities (cityId,countryId,cityName) VALUES (180,174,'Huye');
INSERT INTO cities (cityId,countryId,cityName) VALUES (181,183,'Abha');
INSERT INTO cities (cityId,countryId,cityName) VALUES (182,191,'Honiara');
INSERT INTO cities (cityId,countryId,cityName) VALUES (183,186,'Grand Anse Village');
INSERT INTO cities (cityId,countryId,cityName) VALUES (184,197,'Ad Douiem');
INSERT INTO cities (cityId,countryId,cityName) VALUES (185,200,'Alby');
INSERT INTO cities (cityId,countryId,cityName) VALUES (186,188,'Bedok');
INSERT INTO cities (cityId,countryId,cityName) VALUES (187,190,'Apače');
INSERT INTO cities (cityId,countryId,cityName) VALUES (188,189,'Banska Bystrica');
INSERT INTO cities (cityId,countryId,cityName) VALUES (189,187,'Freetown');
INSERT INTO cities (cityId,countryId,cityName) VALUES (190,181,'San Marino');
INSERT INTO cities (cityId,countryId,cityName) VALUES (191,184,'Dakar');
INSERT INTO cities (cityId,countryId,cityName) VALUES (192,192,'Garoowe');
INSERT INTO cities (cityId,countryId,cityName) VALUES (193,198,'Paramaribo');
INSERT INTO cities (cityId,countryId,cityName) VALUES (194,194,'Conroe');
INSERT INTO cities (cityId,countryId,cityName) VALUES (195,182,'São Tomé');
INSERT INTO cities (cityId,countryId,cityName) VALUES (196,62,'Ahuachapan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (197,202,'Al Tal');
INSERT INTO cities (cityId,countryId,cityName) VALUES (198,199,'Mbabane');
INSERT INTO cities (cityId,countryId,cityName) VALUES (199,215,'Cockburn Town');
INSERT INTO cities (cityId,countryId,cityName) VALUES (200,41,'Ndjamena');
INSERT INTO cities (cityId,countryId,cityName) VALUES (201,208,'Lome');
INSERT INTO cities (cityId,countryId,cityName) VALUES (202,206,'Ban Chan');
INSERT INTO cities (cityId,countryId,cityName) VALUES (203,204,'Dushanbe');
INSERT INTO cities (cityId,countryId,cityName) VALUES (204,209,'Fenua Fala');
INSERT INTO cities (cityId,countryId,cityName) VALUES (205,207,'Dili');
INSERT INTO cities (cityId,countryId,cityName) VALUES (206,214,'Ashgabat');
INSERT INTO cities (cityId,countryId,cityName) VALUES (207,212,'Ben Arous');
INSERT INTO cities (cityId,countryId,cityName) VALUES (208,210,'Nuku''alofa');
INSERT INTO cities (cityId,countryId,cityName) VALUES (209,213,'Adana');
INSERT INTO cities (cityId,countryId,cityName) VALUES (210,211,'Belmont');
INSERT INTO cities (cityId,countryId,cityName) VALUES (211,203,'Anle District');
INSERT INTO cities (cityId,countryId,cityName) VALUES (212,205,'Arusha');
INSERT INTO cities (cityId,countryId,cityName) VALUES (213,217,'Aeroflots''kyi');
INSERT INTO cities (cityId,countryId,cityName) VALUES (214,216,'Kampala');
INSERT INTO cities (cityId,countryId,cityName) VALUES (215,221,'Addison');
INSERT INTO cities (cityId,countryId,cityName) VALUES (216,220,'Aaron');
INSERT INTO cities (cityId,countryId,cityName) VALUES (217,222,'Canelones');
INSERT INTO cities (cityId,countryId,cityName) VALUES (218,223,'Fergana');
INSERT INTO cities (cityId,countryId,cityName) VALUES (219,90,'Roma');
INSERT INTO cities (cityId,countryId,cityName) VALUES (220,179,'Kingstown');
INSERT INTO cities (cityId,countryId,cityName) VALUES (221,225,'Acarigua');
INSERT INTO cities (cityId,countryId,cityName) VALUES (222,227,'Parham Town');
INSERT INTO cities (cityId,countryId,cityName) VALUES (223,228,'Charlotte Amalie');
INSERT INTO cities (cityId,countryId,cityName) VALUES (224,226,'Ba Ria');
INSERT INTO cities (cityId,countryId,cityName) VALUES (225,224,'Port Vila');
INSERT INTO cities (cityId,countryId,cityName) VALUES (226,229,'Matāʻutu');
INSERT INTO cities (cityId,countryId,cityName) VALUES (227,180,'Apia');
INSERT INTO cities (cityId,countryId,cityName) VALUES (228,230,'Dhamar');
INSERT INTO cities (cityId,countryId,cityName) VALUES (229,134,'Mamoudzou');
INSERT INTO cities (cityId,countryId,cityName) VALUES (230,193,'Akasia');
INSERT INTO cities (cityId,countryId,cityName) VALUES (231,231,'Lusaka');
INSERT INTO cities (cityId,countryId,cityName) VALUES (232,232,'Bulawayo');

COMMIT;