INSERT INTO countries (countryId,countryName) VALUES (1,'Afghanistan');
INSERT INTO countries (countryId,countryName) VALUES (2,'Albania');
INSERT INTO countries (countryId,countryName) VALUES (3,'Algeria');
INSERT INTO countries (countryId,countryName) VALUES (4,'American Samoa');
INSERT INTO countries (countryId,countryName) VALUES (5,'Andorra');
INSERT INTO countries (countryId,countryName) VALUES (6,'Angola');
INSERT INTO countries (countryId,countryName) VALUES (7,'Anguilla');
INSERT INTO countries (countryId,countryName) VALUES (8,'Antigua And Barbuda');
INSERT INTO countries (countryId,countryName) VALUES (9,'Argentina');
INSERT INTO countries (countryId,countryName) VALUES (10,'Armenia');
INSERT INTO countries (countryId,countryName) VALUES (11,'Aruba');
INSERT INTO countries (countryId,countryName) VALUES (12,'Australia');
INSERT INTO countries (countryId,countryName) VALUES (13,'Austria');
INSERT INTO countries (countryId,countryName) VALUES (14,'Azerbaijan');
INSERT INTO countries (countryId,countryName) VALUES (15,'Åland Islands');
INSERT INTO countries (countryId,countryName) VALUES (16,'Bahamas');
INSERT INTO countries (countryId,countryName) VALUES (17,'Bahrain');
INSERT INTO countries (countryId,countryName) VALUES (18,'Bangladesh');
INSERT INTO countries (countryId,countryName) VALUES (19,'Barbados');
INSERT INTO countries (countryId,countryName) VALUES (20,'Belarus');
INSERT INTO countries (countryId,countryName) VALUES (21,'Belgium');
INSERT INTO countries (countryId,countryName) VALUES (22,'Belize');
INSERT INTO countries (countryId,countryName) VALUES (23,'Benin');
INSERT INTO countries (countryId,countryName) VALUES (24,'Bermuda');
INSERT INTO countries (countryId,countryName) VALUES (25,'Bhutan');
INSERT INTO countries (countryId,countryName) VALUES (26,'Bolivia, Plurinational State Of');
INSERT INTO countries (countryId,countryName) VALUES (27,'Bonaire, Sint Eustatius And Saba');
INSERT INTO countries (countryId,countryName) VALUES (28,'Bosnia And Herzegovina');
INSERT INTO countries (countryId,countryName) VALUES (29,'Botswana');
INSERT INTO countries (countryId,countryName) VALUES (30,'Brazil');
INSERT INTO countries (countryId,countryName) VALUES (31,'Brunei Darussalam');
INSERT INTO countries (countryId,countryName) VALUES (32,'Bulgaria');
INSERT INTO countries (countryId,countryName) VALUES (33,'Burkina Faso');
INSERT INTO countries (countryId,countryName) VALUES (34,'Burundi');
INSERT INTO countries (countryId,countryName) VALUES (35,'Cambodia');
INSERT INTO countries (countryId,countryName) VALUES (36,'Cameroon');
INSERT INTO countries (countryId,countryName) VALUES (37,'Canada');
INSERT INTO countries (countryId,countryName) VALUES (38,'Cape Verde');
INSERT INTO countries (countryId,countryName) VALUES (39,'Cayman Islands');
INSERT INTO countries (countryId,countryName) VALUES (40,'Central African Republic');
INSERT INTO countries (countryId,countryName) VALUES (41,'Chad');
INSERT INTO countries (countryId,countryName) VALUES (42,'Chile');
INSERT INTO countries (countryId,countryName) VALUES (43,'China');
INSERT INTO countries (countryId,countryName) VALUES (44,'Colombia');
INSERT INTO countries (countryId,countryName) VALUES (45,'Comoros');
INSERT INTO countries (countryId,countryName) VALUES (46,'Congo');
INSERT INTO countries (countryId,countryName) VALUES (47,'Congo, The Democratic Republic Of The');
INSERT INTO countries (countryId,countryName) VALUES (48,'Cook Islands');
INSERT INTO countries (countryId,countryName) VALUES (49,'Costa Rica');
INSERT INTO countries (countryId,countryName) VALUES (50,'Côte D''Ivoire');
INSERT INTO countries (countryId,countryName) VALUES (51,'Croatia');
INSERT INTO countries (countryId,countryName) VALUES (52,'Cuba');
INSERT INTO countries (countryId,countryName) VALUES (53,'Curaçao');
INSERT INTO countries (countryId,countryName) VALUES (54,'Cyprus');
INSERT INTO countries (countryId,countryName) VALUES (55,'Czech Republic');
INSERT INTO countries (countryId,countryName) VALUES (56,'Denmark');
INSERT INTO countries (countryId,countryName) VALUES (57,'Djibouti');
INSERT INTO countries (countryId,countryName) VALUES (58,'Dominica');
INSERT INTO countries (countryId,countryName) VALUES (59,'Dominican Republic');
INSERT INTO countries (countryId,countryName) VALUES (60,'Ecuador');
INSERT INTO countries (countryId,countryName) VALUES (61,'Egypt');
INSERT INTO countries (countryId,countryName) VALUES (62,'El Salvador');
INSERT INTO countries (countryId,countryName) VALUES (63,'Equatorial Guinea');
INSERT INTO countries (countryId,countryName) VALUES (64,'Eritrea');
INSERT INTO countries (countryId,countryName) VALUES (65,'Estonia');
INSERT INTO countries (countryId,countryName) VALUES (66,'Ethiopia');
INSERT INTO countries (countryId,countryName) VALUES (67,'Falkland Islands (Malvinas)');
INSERT INTO countries (countryId,countryName) VALUES (68,'Faroe Islands');
INSERT INTO countries (countryId,countryName) VALUES (69,'Fiji');
INSERT INTO countries (countryId,countryName) VALUES (70,'Finland');
INSERT INTO countries (countryId,countryName) VALUES (71,'France');
INSERT INTO countries (countryId,countryName) VALUES (72,'French Guiana');
INSERT INTO countries (countryId,countryName) VALUES (73,'French Polynesia');
INSERT INTO countries (countryId,countryName) VALUES (74,'Gabon');
INSERT INTO countries (countryId,countryName) VALUES (75,'Gambia');
INSERT INTO countries (countryId,countryName) VALUES (76,'Georgia');
INSERT INTO countries (countryId,countryName) VALUES (77,'Germany');
INSERT INTO countries (countryId,countryName) VALUES (78,'Ghana');
INSERT INTO countries (countryId,countryName) VALUES (79,'Gibraltar');
INSERT INTO countries (countryId,countryName) VALUES (80,'Greece');
INSERT INTO countries (countryId,countryName) VALUES (81,'Greenland');
INSERT INTO countries (countryId,countryName) VALUES (82,'Grenada');
INSERT INTO countries (countryId,countryName) VALUES (83,'Guadeloupe');
INSERT INTO countries (countryId,countryName) VALUES (84,'Guam');
INSERT INTO countries (countryId,countryName) VALUES (85,'Guatemala');
INSERT INTO countries (countryId,countryName) VALUES (86,'Guinea');
INSERT INTO countries (countryId,countryName) VALUES (87,'Guinea-Bissau');
INSERT INTO countries (countryId,countryName) VALUES (88,'Guyana');
INSERT INTO countries (countryId,countryName) VALUES (89,'Haiti');
INSERT INTO countries (countryId,countryName) VALUES (90,'Holy See (Vatican City State)');
INSERT INTO countries (countryId,countryName) VALUES (91,'Honduras');
INSERT INTO countries (countryId,countryName) VALUES (92,'Hong Kong');
INSERT INTO countries (countryId,countryName) VALUES (93,'Hungary');
INSERT INTO countries (countryId,countryName) VALUES (94,'Iceland');
INSERT INTO countries (countryId,countryName) VALUES (95,'India');
INSERT INTO countries (countryId,countryName) VALUES (96,'Indonesia');
INSERT INTO countries (countryId,countryName) VALUES (97,'Iran, Islamic Republic Of');
INSERT INTO countries (countryId,countryName) VALUES (98,'Iraq');
INSERT INTO countries (countryId,countryName) VALUES (99,'Ireland');
INSERT INTO countries (countryId,countryName) VALUES (100,'Isle Of Man');
INSERT INTO countries (countryId,countryName) VALUES (101,'Israel');
INSERT INTO countries (countryId,countryName) VALUES (102,'Italy');
INSERT INTO countries (countryId,countryName) VALUES (103,'Jamaica');
INSERT INTO countries (countryId,countryName) VALUES (104,'Japan');
INSERT INTO countries (countryId,countryName) VALUES (105,'Jersey');
INSERT INTO countries (countryId,countryName) VALUES (106,'Jordan');
INSERT INTO countries (countryId,countryName) VALUES (107,'Kazakhstan');
INSERT INTO countries (countryId,countryName) VALUES (108,'Kenya');
INSERT INTO countries (countryId,countryName) VALUES (109,'Kiribati');
INSERT INTO countries (countryId,countryName) VALUES (110,'Korea, Republic Of');
INSERT INTO countries (countryId,countryName) VALUES (111,'Kuwait');
INSERT INTO countries (countryId,countryName) VALUES (112,'Kyrgyzstan');
INSERT INTO countries (countryId,countryName) VALUES (113,'Lao People''S Democratic Republic');
INSERT INTO countries (countryId,countryName) VALUES (114,'Latvia');
INSERT INTO countries (countryId,countryName) VALUES (115,'Lebanon');
INSERT INTO countries (countryId,countryName) VALUES (116,'Lesotho');
INSERT INTO countries (countryId,countryName) VALUES (117,'Liberia');
INSERT INTO countries (countryId,countryName) VALUES (118,'Libya');
INSERT INTO countries (countryId,countryName) VALUES (119,'Liechtenstein');
INSERT INTO countries (countryId,countryName) VALUES (120,'Lithuania');
INSERT INTO countries (countryId,countryName) VALUES (121,'Luxembourg');
INSERT INTO countries (countryId,countryName) VALUES (122,'Macao');
INSERT INTO countries (countryId,countryName) VALUES (123,'Macedonia, The Former Yugoslav Republic Of');
INSERT INTO countries (countryId,countryName) VALUES (124,'Madagascar');
INSERT INTO countries (countryId,countryName) VALUES (125,'Malawi');
INSERT INTO countries (countryId,countryName) VALUES (126,'Malaysia');
INSERT INTO countries (countryId,countryName) VALUES (127,'Maldives');
INSERT INTO countries (countryId,countryName) VALUES (128,'Mali');
INSERT INTO countries (countryId,countryName) VALUES (129,'Malta');
INSERT INTO countries (countryId,countryName) VALUES (130,'Marshall Islands');
INSERT INTO countries (countryId,countryName) VALUES (131,'Martinique');
INSERT INTO countries (countryId,countryName) VALUES (132,'Mauritania');
INSERT INTO countries (countryId,countryName) VALUES (133,'Mauritius');
INSERT INTO countries (countryId,countryName) VALUES (134,'Mayotte');
INSERT INTO countries (countryId,countryName) VALUES (135,'Mexico');
INSERT INTO countries (countryId,countryName) VALUES (136,'Micronesia, Federated States Of');
INSERT INTO countries (countryId,countryName) VALUES (137,'Moldova, Republic Of');
INSERT INTO countries (countryId,countryName) VALUES (138,'Monaco');
INSERT INTO countries (countryId,countryName) VALUES (139,'Mongolia');
INSERT INTO countries (countryId,countryName) VALUES (140,'Montenegro');
INSERT INTO countries (countryId,countryName) VALUES (141,'Montserrat');
INSERT INTO countries (countryId,countryName) VALUES (142,'Morocco');
INSERT INTO countries (countryId,countryName) VALUES (143,'Mozambique');
INSERT INTO countries (countryId,countryName) VALUES (144,'Myanmar');
INSERT INTO countries (countryId,countryName) VALUES (145,'Namibia');
INSERT INTO countries (countryId,countryName) VALUES (146,'Nauru');
INSERT INTO countries (countryId,countryName) VALUES (147,'Nepal');
INSERT INTO countries (countryId,countryName) VALUES (148,'Netherlands');
INSERT INTO countries (countryId,countryName) VALUES (149,'Netherlands Antilles');
INSERT INTO countries (countryId,countryName) VALUES (150,'New Caledonia');
INSERT INTO countries (countryId,countryName) VALUES (151,'New Zealand');
INSERT INTO countries (countryId,countryName) VALUES (152,'Nicaragua');
INSERT INTO countries (countryId,countryName) VALUES (153,'Niger');
INSERT INTO countries (countryId,countryName) VALUES (154,'Nigeria');
INSERT INTO countries (countryId,countryName) VALUES (155,'Niue');
INSERT INTO countries (countryId,countryName) VALUES (156,'Northern Mariana Islands');
INSERT INTO countries (countryId,countryName) VALUES (157,'Norway');
INSERT INTO countries (countryId,countryName) VALUES (158,'Oman');
INSERT INTO countries (countryId,countryName) VALUES (159,'Pakistan');
INSERT INTO countries (countryId,countryName) VALUES (160,'Palau');
INSERT INTO countries (countryId,countryName) VALUES (161,'Palestine, State Of');
INSERT INTO countries (countryId,countryName) VALUES (162,'Panama');
INSERT INTO countries (countryId,countryName) VALUES (163,'Papua New Guinea');
INSERT INTO countries (countryId,countryName) VALUES (164,'Paraguay');
INSERT INTO countries (countryId,countryName) VALUES (165,'Peru');
INSERT INTO countries (countryId,countryName) VALUES (166,'Philippines');
INSERT INTO countries (countryId,countryName) VALUES (167,'Poland');
INSERT INTO countries (countryId,countryName) VALUES (168,'Portugal');
INSERT INTO countries (countryId,countryName) VALUES (169,'Puerto Rico');
INSERT INTO countries (countryId,countryName) VALUES (170,'Qatar');
INSERT INTO countries (countryId,countryName) VALUES (171,'Réunion');
INSERT INTO countries (countryId,countryName) VALUES (172,'Romania');
INSERT INTO countries (countryId,countryName) VALUES (173,'Russian Federation');
INSERT INTO countries (countryId,countryName) VALUES (174,'Rwanda');
INSERT INTO countries (countryId,countryName) VALUES (175,'Saint Kitts And Nevis');
INSERT INTO countries (countryId,countryName) VALUES (176,'Saint Lucia');
INSERT INTO countries (countryId,countryName) VALUES (177,'Saint Martin (French Part)');
INSERT INTO countries (countryId,countryName) VALUES (178,'Saint Pierre And Miquelon');
INSERT INTO countries (countryId,countryName) VALUES (179,'Saint Vincent And The Grenadines');
INSERT INTO countries (countryId,countryName) VALUES (180,'Samoa');
INSERT INTO countries (countryId,countryName) VALUES (181,'San Marino');
INSERT INTO countries (countryId,countryName) VALUES (182,'Sao Tome And Principe');
INSERT INTO countries (countryId,countryName) VALUES (183,'Saudi Arabia');
INSERT INTO countries (countryId,countryName) VALUES (184,'Senegal');
INSERT INTO countries (countryId,countryName) VALUES (185,'Serbia');
INSERT INTO countries (countryId,countryName) VALUES (186,'Seychelles');
INSERT INTO countries (countryId,countryName) VALUES (187,'Sierra Leone');
INSERT INTO countries (countryId,countryName) VALUES (188,'Singapore');
INSERT INTO countries (countryId,countryName) VALUES (189,'Slovakia');
INSERT INTO countries (countryId,countryName) VALUES (190,'Slovenia');
INSERT INTO countries (countryId,countryName) VALUES (191,'Solomon Islands');
INSERT INTO countries (countryId,countryName) VALUES (192,'Somalia');
INSERT INTO countries (countryId,countryName) VALUES (193,'South Africa');
INSERT INTO countries (countryId,countryName) VALUES (194,'South Sudan');
INSERT INTO countries (countryId,countryName) VALUES (195,'Spain');
INSERT INTO countries (countryId,countryName) VALUES (196,'Sri Lanka');
INSERT INTO countries (countryId,countryName) VALUES (197,'Sudan');
INSERT INTO countries (countryId,countryName) VALUES (198,'Suriname');
INSERT INTO countries (countryId,countryName) VALUES (199,'Swaziland');
INSERT INTO countries (countryId,countryName) VALUES (200,'Sweden');
INSERT INTO countries (countryId,countryName) VALUES (201,'Switzerland');
INSERT INTO countries (countryId,countryName) VALUES (202,'Syrian Arab Republic');
INSERT INTO countries (countryId,countryName) VALUES (203,'Taiwan, Province Of China');
INSERT INTO countries (countryId,countryName) VALUES (204,'Tajikistan');
INSERT INTO countries (countryId,countryName) VALUES (205,'Tanzania, United Republic Of');
INSERT INTO countries (countryId,countryName) VALUES (206,'Thailand');
INSERT INTO countries (countryId,countryName) VALUES (207,'Timor-Leste');
INSERT INTO countries (countryId,countryName) VALUES (208,'Togo');
INSERT INTO countries (countryId,countryName) VALUES (209,'Tokelau');
INSERT INTO countries (countryId,countryName) VALUES (210,'Tonga');
INSERT INTO countries (countryId,countryName) VALUES (211,'Trinidad And Tobago');
INSERT INTO countries (countryId,countryName) VALUES (212,'Tunisia');
INSERT INTO countries (countryId,countryName) VALUES (213,'Turkey');
INSERT INTO countries (countryId,countryName) VALUES (214,'Turkmenistan');
INSERT INTO countries (countryId,countryName) VALUES (215,'Turks And Caicos Islands');
INSERT INTO countries (countryId,countryName) VALUES (216,'Uganda');
INSERT INTO countries (countryId,countryName) VALUES (217,'Ukraine');
INSERT INTO countries (countryId,countryName) VALUES (218,'United Arab Emirates');
INSERT INTO countries (countryId,countryName) VALUES (219,'United Kingdom');
INSERT INTO countries (countryId,countryName) VALUES (220,'United States');
INSERT INTO countries (countryId,countryName) VALUES (221,'United States Minor Outlying Islands');
INSERT INTO countries (countryId,countryName) VALUES (222,'Uruguay');
INSERT INTO countries (countryId,countryName) VALUES (223,'Uzbekistan');
INSERT INTO countries (countryId,countryName) VALUES (224,'Vanuatu');
INSERT INTO countries (countryId,countryName) VALUES (225,'Venezuela, Bolivarian Republic Of');
INSERT INTO countries (countryId,countryName) VALUES (226,'Viet Nam');
INSERT INTO countries (countryId,countryName) VALUES (227,'Virgin Islands, British');
INSERT INTO countries (countryId,countryName) VALUES (228,'Virgin Islands, U.S.');
INSERT INTO countries (countryId,countryName) VALUES (229,'Wallis And Futuna');
INSERT INTO countries (countryId,countryName) VALUES (230,'Yemen');
INSERT INTO countries (countryId,countryName) VALUES (231,'Zambia');
INSERT INTO countries (countryId,countryName) VALUES (232,'Zimbabwe');

COMMIT;