INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (1,1,'Animation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (2,1,'Architecture');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (3,1,'Art History');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (4,1,'Artists');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (5,1,'Arts and Crafts');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (6,1,'Awards');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (7,1,'Body Art');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (8,1,'Bodyart');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (9,1,'Ceramics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (10,1,'Classical Studies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (11,1,'Comics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (12,1,'Computer Generated');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (13,1,'Costumes');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (14,1,'Crafts');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (15,1,'Cultures and Groups');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (16,1,'Design');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (17,1,'Digital');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (18,1,'Directories');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (19,1,'Entertainment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (20,1,'Genres');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (21,1,'Graphic Design');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (22,1,'Humanities');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (23,1,'Illustration');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (24,1,'Literature');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (25,1,'Movies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (26,1,'Music');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (27,1,'Online Writing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (28,1,'Organizations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (29,1,'Performing Arts');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (30,1,'Periods and Movements');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (31,1,'Photography');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (32,1,'Quilting');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (33,1,'Radio');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (34,1,'Sculpture');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (35,1,'Television');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (36,1,'Video');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (37,1,'Visual Arts');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (38,1,'Writers Resources');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (39,2,'Accounting');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (40,2,'Advertising');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (41,2,'Aerospace and Defense');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (42,2,'Agriculture');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (43,2,'Agriculture and Forestry');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (44,2,'Arts and Entertainment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (45,2,'Associations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (46,2,'Automotive');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (47,2,'Banking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (48,2,'Biotechnology and Pharmaceuticals');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (49,2,'Business and Society');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (50,2,'Business Services');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (51,2,'Chemicals');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (52,2,'Construction');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (53,2,'Construction and Maintenance');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (54,2,'Consulting');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (55,2,'Consumer Goods and Services');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (56,2,'Cooperatives');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (57,2,'Customer Service');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (58,2,'Education and Training');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (59,2,'Electronics and Electrical');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (60,2,'Employment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (61,2,'Energy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (62,2,'Environment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (63,2,'Financial');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (64,2,'Financial Services');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (65,2,'Food');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (66,2,'Food and Related Products');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (67,2,'Healthcare');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (68,2,'Hospitality');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (69,2,'Human Resources');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (70,2,'Industrial Goods and Services');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (71,2,'Information Services');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (72,2,'Information Technology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (73,2,'Insurance');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (74,2,'International Business and Trade');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (75,2,'Internet');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (76,2,'Investing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (77,2,'Legal');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (78,2,'Major Companies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (79,2,'Management');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (80,2,'Manufacturing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (81,2,'Marketing and Advertising');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (82,2,'Marketing and Sales');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (83,2,'Materials');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (84,2,'Mining');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (85,2,'Mining and Drilling');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (86,2,'Opportunities');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (87,2,'Publishing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (88,2,'Publishing and Printing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (89,2,'Real Estate');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (90,2,'Resources');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (91,2,'Retail Trade');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (92,2,'Security');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (93,2,'Small Business');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (94,2,'Telecommunications');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (95,2,'Textiles and Nonwovens');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (96,2,'Transportation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (97,2,'Transportation and Logistics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (98,2,'Wholesale Trade');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (99,3,'Algorithms');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (100,3,'Artificial Intelligence');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (101,3,'Artificial Life');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (102,3,'Automation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (103,3,'Bulletin Board Systems');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (104,3,'CAD and CAM');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (105,3,'Companies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (106,3,'Computer Arts');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (107,3,'Computer Science');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (108,3,'Consultants');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (109,3,'Data Communications');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (110,3,'Data Formats');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (111,3,'Databases');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (112,3,'Desktop Publishing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (113,3,'E-Books');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (114,3,'E-Commerce');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (115,3,'Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (116,3,'Emulators');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (117,3,'Ethics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (118,3,'Games');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (119,3,'Graphics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (120,3,'Hacking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (121,3,'Hardware');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (122,3,'History');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (123,3,'Home Automation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (124,3,'Human-Computer Interaction');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (125,3,'Internet');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (126,3,'Intranet');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (127,3,'Java');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (128,3,'Macintosh');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (129,3,'Microprocessors');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (130,3,'Mobile Computing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (131,3,'Multimedia');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (132,3,'Networking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (133,3,'Object Oriented');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (134,3,'Open Source');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (135,3,'Operating Systems');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (136,3,'Organizations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (137,3,'Parallel Computing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (138,3,'Performance and Capacity');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (139,3,'Programming');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (140,3,'Programming Languages');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (141,3,'Robotics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (142,3,'Security');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (143,3,'Software');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (144,3,'Speech Technology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (145,3,'Supercomputing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (146,3,'Systems');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (147,3,'Unix');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (148,3,'Usenet');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (149,3,'Virtual Reality');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (150,3,'World Wide Web');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (151,4,'Apartment Living');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (152,4,'Consumer Information');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (153,4,'Cooking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (154,4,'Do-It-Yourself');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (155,4,'Emergency Preparation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (156,4,'Entertaining');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (157,4,'Family');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (158,4,'Gardening');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (159,4,'Home Improvement');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (160,4,'Homemaking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (161,4,'Homeowners');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (162,4,'Moving and Relocating');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (163,4,'Personal Finance');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (164,4,'Personal Organization');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (165,4,'Rural Living');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (166,4,'Urban Living');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (167,5,'Adolescence Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (168,5,'Adult Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (169,5,'Advanced Quantitative Methods in Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (170,5,'Business Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (171,5,'Christian School Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (172,5,'Communication Disorders and Sciences');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (173,5,'Community Development and Action');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (174,5,'Critical and Socio-cultural Studies in Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (175,5,'Curriculum and Instruction');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (176,5,'Distance Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (177,5,'Early Childhood Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (178,5,'Education for Hearing Impaired');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (179,5,'Educational Administration');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (180,5,'Educational Leadership');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (181,5,'Elementary Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (182,5,'English as a Second Language');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (183,5,'English Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (184,5,'Environmental Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (185,5,'Financial Aid');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (186,5,'General Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (187,5,'Health Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (188,5,'Higher Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (189,5,'History Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (190,5,'Home Schooling');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (191,5,'Human Resource Development');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (192,5,'Information Studies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (193,5,'Instructional Technology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (194,5,'International Comparative Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (195,5,'K12 Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (196,5,'Languages');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (197,5,'Learning and Organizational Change');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (198,5,'Learning Diversity and Urban Studies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (199,5,'Library Resource Management');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (200,5,'Literacy Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (201,5,'Math Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (202,5,'Middle Grades Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (203,5,'Mind Brain and Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (204,5,'Montessori Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (205,5,'Music Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (206,5,'Physical Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (207,5,'Reading Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (208,5,'Research Art Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (209,5,'Risk and Prevention');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (210,5,'School Counseling');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (211,5,'School Health Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (212,5,'School Psychology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (213,5,'School Safety');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (214,5,'Science Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (215,5,'Secondary Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (216,5,'Social Research Methodology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (217,5,'Social Studies Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (218,5,'Special Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (219,5,'Talented and Gifted Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (220,5,'Teacher Education Program');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (221,5,'Technical and Vocational');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (222,5,'Technology Innovation and Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (223,5,'Visually Impaired Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (224,6,'Africa');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (225,6,'Asia');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (226,6,'Caribbean');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (227,6,'Central America');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (228,6,'Countries');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (229,6,'Europe');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (230,6,'Middle East');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (231,6,'Middle East');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (232,6,'North America');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (233,6,'Oceania');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (234,6,'Polar Regions');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (235,6,'South America');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (236,7,'Addictions');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (237,7,'Aging');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (238,7,'AIDS');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (239,7,'Alternative');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (240,7,'Animal');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (241,7,'Beauty');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (242,7,'Child Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (243,7,'Conditions and Diseases');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (244,7,'Dentistry');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (245,7,'Disabilities');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (246,7,'Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (247,7,'Environmental');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (248,7,'Fitness');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (249,7,'Home Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (250,7,'Insurance');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (251,7,'Long Term');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (252,7,'Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (253,7,'Men''s Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (254,7,'Mental');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (255,7,'Mental Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (256,7,'Neurology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (257,7,'Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (258,7,'Nutrition');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (259,7,'Occupational Health and Safety');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (260,7,'Organizations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (261,7,'Pharmacy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (262,7,'Physiology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (263,7,'Professions');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (264,7,'Public Health and Safety');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (265,7,'Publications');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (266,7,'Reproductive Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (267,7,'Resources');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (268,7,'Senior Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (269,7,'Senses');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (270,7,'Services');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (271,7,'Specific Substances');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (272,7,'Teen Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (273,7,'Veterinary');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (274,7,'Weight Loss');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (275,7,'Women''s Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (276,8,'Administrative and Regulatory');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (277,8,'Admiralty and Maritime');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (278,8,'Air Sea and Space');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (279,8,'Antitrust');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (280,8,'Appellate');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (281,8,'Banking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (282,8,'Bankruptcy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (283,8,'Business');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (284,8,'Business Bankruptcy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (285,8,'Childrens Advocacy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (286,8,'Civil Rights');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (287,8,'Civil Trial Advocacy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (288,8,'Consumer Bankruptcy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (289,8,'Creditors Rights');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (290,8,'Criminal');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (291,8,'Criminal Trial Advocacy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (292,8,'Cyberspace');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (293,8,'Disability');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (294,8,'Drug');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (295,8,'e-Commerce');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (296,8,'Elder');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (297,8,'Employment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (298,8,'Entertainment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (299,8,'Environmental');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (300,8,'Estate Planning Trust and Probate');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (301,8,'Family');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (302,8,'Family Trial Advocacy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (303,8,'Fashion');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (304,8,'Franchise and Distribution');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (305,8,'Gaming');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (306,8,'Health');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (307,8,'Immigration and Nationality');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (308,8,'Insurance');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (309,8,'Intellectual Property');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (310,8,'Judicial');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (311,8,'Legal Malpractice');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (312,8,'Legal Professional Liability');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (313,8,'Litigation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (314,8,'Medical Professional Liability');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (315,8,'Military');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (316,8,'National Security');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (317,8,'Personal Injury');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (318,8,'Privacy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (319,8,'Property');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (320,8,'Public Defense');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (321,8,'Real Estate');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (322,8,'Securities');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (323,8,'Social Security Disability');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (324,8,'Sports');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (325,8,'Taxation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (326,8,'Workers Compensation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (327,9,'Aerospace Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (328,9,'Allergy and Immunology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (329,9,'Anesthesiology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (330,9,'Child Neurology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (331,9,'Clinical Biochemical Genetics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (332,9,'Clinical Cytogenetics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (333,9,'Clinical Genetics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (334,9,'Clinical Molecular Genetics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (335,9,'CME');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (336,9,'Colon and Rectal Surgery');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (337,9,'Continuing Medical Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (338,9,'Dermatology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (339,9,'Diagnostic Radiology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (340,9,'Emergency Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (341,9,'Family Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (342,9,'Internal Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (343,9,'Medical Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (344,9,'Medical Physics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (345,9,'Neurological Surgery');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (346,9,'Neurology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (347,9,'Nuclear Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (348,9,'Obstetrics and Gynecology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (349,9,'Occupational Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (350,9,'Oncology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (351,9,'Otolaryngology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (352,9,'Pathology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (353,9,'Pediatrics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (354,9,'Physical Medicine and Rehabilitation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (355,9,'Plastic Surgery');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (356,9,'Psychiatry');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (357,9,'Public Health and General Preventive Medicine');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (358,9,'Radiation Oncology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (359,9,'Surgery');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (360,9,'Thoracic and Cardiac Surgery');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (361,9,'Urology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (362,9,'Vascular Surgery');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (363,10,'Colleges and Universities');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (364,10,'Current Events');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (365,10,'Internet');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (366,10,'Magazines');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (367,10,'Media');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (368,10,'Newspapers');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (369,10,'Photojournalism');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (370,10,'Radio');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (371,10,'Television');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (372,10,'Weather');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (373,11,'Addictions Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (374,11,'Agency Nurses');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (375,11,'Ambulatory Care Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (376,11,'Burn Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (377,11,'Camp Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (378,11,'Cardiac Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (379,11,'Case Management Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (380,11,'Clinic Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (381,11,'Community Health Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (382,11,'Continence');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (383,11,'Correctional Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (384,11,'Developmental Disabilities');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (385,11,'Diabetes');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (386,11,'Dialysis');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (387,11,'Directors Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (388,11,'Emergency Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (389,11,'Endocrine Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (390,11,'Entrepreneurs in Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (391,11,'Flight Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (392,11,'Forensic Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (393,11,'Gastroenterology Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (394,11,'Geriatric Nurses');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (395,11,'Government Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (396,11,'Government Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (397,11,'Holistic Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (398,11,'Home Health Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (399,11,'Hospice Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (400,11,'Hyperbaric Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (401,11,'Infectious Disease Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (402,11,'Infusion Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (403,11,'LTC Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (404,11,'MDS Coordinator Information');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (405,11,'Medical-Surgical Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (406,11,'Military Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (407,11,'Neurological Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (408,11,'Nurse Massage Therapists');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (409,11,'Nurse Staff Development');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (410,11,'Nursing Educators');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (411,11,'Nursing Faculty');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (412,11,'Nursing Informatics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (413,11,'Nursing Management');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (414,11,'Ob-Gyn Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (415,11,'Occupational Health Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (416,11,'Oncology Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (417,11,'Operating Room Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (418,11,'Orthopaedic Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (419,11,'Ostomy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (420,11,'PACU Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (421,11,'Pain Management Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (422,11,'Parish Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (423,11,'Pediatric Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (424,11,'Private Duty Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (425,11,'Psychiatric Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (426,11,'Public Health Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (427,11,'Pulmonary Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (428,11,'Quality Improvement');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (429,11,'Radiology Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (430,11,'Rehabilitation Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (431,11,'Renal');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (432,11,'Research Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (433,11,'Rural Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (434,11,'School Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (435,11,'Surface Transport Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (436,11,'Telephone Triage Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (437,11,'Travel Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (438,11,'Urology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (439,11,'Volunteer Nursing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (440,11,'Wound');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (441,12,'Antiques');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (442,12,'Audio');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (443,12,'Autos');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (444,12,'Aviation');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (445,12,'Birding');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (446,12,'Boating');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (447,12,'Camps');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (448,12,'Climbing');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (449,12,'Collecting');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (450,12,'Drugs');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (451,12,'Games');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (452,12,'Gardens');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (453,12,'Guns');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (454,12,'Humor');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (455,12,'Kites');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (456,12,'Knives');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (457,12,'Living History');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (458,12,'Locks');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (459,12,'Models');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (460,12,'Motorcycles');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (461,12,'Nu');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (462,12,'Outdoors');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (463,12,'Parties');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (464,12,'Pets');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (465,12,'Picture Ratings');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (466,12,'Radio');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (467,12,'Roads and Highways');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (468,12,'Scouting');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (469,12,'Shopping');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (470,12,'Smoking');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (471,12,'Sports');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (472,12,'Theme Parks');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (473,12,'Tobacco');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (474,12,'Trains and Railroads');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (475,12,'Travel');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (476,13,'Almanacs');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (477,13,'Archives');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (478,13,'Ask an Expert');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (479,13,'Bibliography');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (480,13,'Biography');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (481,13,'Books');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (482,13,'Dictionaries');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (483,13,'Directories');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (484,13,'Education');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (485,13,'Encyclopedias');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (486,13,'Flags');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (487,13,'Geography');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (488,13,'Knots');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (489,13,'Knowledge Management');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (490,13,'Libraries');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (491,13,'Museums');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (492,13,'Parliamentary Procedure');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (493,13,'Quotations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (494,13,'Thesauri');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (495,13,'Time');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (496,14,'Aeronautics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (497,14,'Agriculture');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (498,14,'Alternative');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (499,14,'Anomalies and Alternative Science');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (500,14,'Astronomy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (501,14,'Biochemistry');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (502,14,'Biology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (503,14,'Biotechnology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (504,14,'Chemistry');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (505,14,'Civil');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (506,14,'Earth Science');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (507,14,'Earth Sciences');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (508,14,'Ecology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (509,14,'Educational Resources');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (510,14,'Electronics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (511,14,'Employment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (512,14,'Energy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (513,14,'Engineering');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (514,14,'Environment');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (515,14,'Forensics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (516,14,'Forestry');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (517,14,'Geography');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (518,14,'Geology and Geophysics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (519,14,'Information Technology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (520,14,'Instruments and Supplies');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (521,14,'Life Sciences');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (522,14,'Mathematics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (523,14,'Mechanical');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (524,14,'Meteorology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (525,14,'Methods and Techniques');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (526,14,'Nanotechnology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (527,14,'Oceanography');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (528,14,'Organizations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (529,14,'Paleontology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (530,14,'Physics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (531,14,'Policy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (532,14,'Psychology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (533,14,'Reference');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (534,14,'Research');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (535,14,'Science in Society');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (536,14,'Social Sciences');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (537,14,'Space');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (538,14,'Sports');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (539,14,'Technology');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (540,14,'Vibrations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (541,14,'Visual Languages');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (542,14,'Wireless');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (543,15,'Activism');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (544,15,'Advice');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (545,15,'Crime');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (546,15,'Death');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (547,15,'Disabled');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (548,15,'Ethnicity');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (549,15,'Families');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (550,15,'Fashion');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (551,15,'Firearms');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (552,15,'Folklore');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (553,15,'Future');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (554,15,'Gay');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (555,15,'Gay, Lesbian, and Bisexual');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (556,15,'Genealogy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (557,15,'Government');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (558,15,'History');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (559,15,'Holidays');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (560,15,'Issues');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (561,15,'Law');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (562,15,'Lifestyle Choices');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (563,15,'Men');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (564,15,'Military');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (565,15,'Mythology and Folklore');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (566,15,'Organizations');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (567,15,'Paranormal');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (568,15,'Philanthropy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (569,15,'Philosophy');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (570,15,'Politics');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (571,15,'Relationships');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (572,15,'Religion and Spirituality');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (573,15,'Sexuality');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (574,15,'Subcultures');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (575,15,'Transgendered');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (576,15,'Weddings');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (577,15,'Women');
INSERT INTO sub_categories (subCategoryId,mainCategoryId,subCategoryName) VALUES (578,15,'Work');

COMMIT;